- src/copyPublicFolder.js
Resolving issue https://github.com/nozzle/react-static/issues/1.
> Fix for missing public folder

- .babelrc
- package.json
Add babel stage-3 preset so that node >=v7.6 could use the async function.
> Node6 compatibilty

- examples/basic/.gitignore
- examples/basic/.npmignore
- examples/basic/gitignore
- examples/custom-routing/.npmignore
- examples/custom-routing/gitignore
- examples/glamorous/.gitignore
- examples/glamorous/gitignore
- examples/styled-components/.gitignore
- examples/styled-components/gitignore
- src/commands/create.js
Solution based on `create-react-app`
> Fix .gitignore file not being copied over from the template

- src/index.js
Thank you for your hard work on react-static. I get goosebumps just experimenting with this masterpiece of a project.
This MR adds a new component `PrefetchWhenSeen`, which will fire the prefetch of its path when it is visible in the view. This opens up for powerful techniques like e.g. prefetching a page when the user first sees a link to it:
```javascript
<PrefetchWhenSeen path={`/blog/post/${post.id}/`}>
<Link to={`/blog/post/${post.id}/`}>{post.title}</Link>
</PrefetchWhenSeen>
```
Is this something you are interested in? The reason why I didn't put a new prop on the `Prefetch` component and add it conditionally that way, is because `Prefetch` has no wrapping element, so I could not put a `ref` on it.
> [WIP] Add Intersection Observer support to Prefetch component

- src/static.js
This update significantly improves the build times for larger sites. For extremely large sites, I am finding anywhere between 2x and 5x faster.
Not only is it faster, but inherently has a larger capacity now. Where 10,000 pages might have seemed daunting, the basic template with 10,000 posts builds in 40 seconds on my machine. Results my vary by machine and CI, but regardless, things are much faster.
> Faster builds via better dynamic route generation

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
Also removed duplicate entry from ```.gitignore``` and added ```#editors``` to ignore editor generated files.
> Added PULL_REQUEST_TEMPLATE.md and updated .gitignore

- README.md
> Add Timber.io to sites built with react-static

- examples/less-antdesign/package.json
- examples/less-antdesign/static.config.js
- examples/typescript/README.md
- examples/typescript/package.json
> Update TS & Antd Example: Updating Dependencies & Fix Ant-Design / Momentjs Rv16 incop

- examples/custom-routing/README.md
> Couple minor consistency improvements in examples/custom-routing/README.md

- examples/apollo-redux/README.md
- examples/apollo/README.md
- examples/blank/README.md
- examples/redux/README.md
Fix wrong description of these examples:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nozzle/react-static/151)
> Fix description of examples: Blank, Redux, Apollo, Apollo and Redux

- src/static.js
This PR makes the Helmet rendering synchronous. Race conditions are introduced if there is any asynchronous logic between `renderToHtml` and `renderStatic`, which can make the header tags end up all over the place in your static files. 
No breaking change is introduced, and `config.renderToHtml` can still be asynchronous. Closes https://github.com/nozzle/react-static/issues/117.
> Make Helmet rendering synchronous

- src/static.js
Please see issue #188 for details.
> Update static.js to fix issue #188

- examples/styled-components/.babelrc
- examples/styled-components/package.json
Make debugging a little easier 🙂
> Added babel-plugin-styled-components to styled-components template.

- examples/graphql-request/.babelrc
- examples/graphql-request/.eslintrc.js
- examples/graphql-request/.gitignore
- examples/graphql-request/README.md
- examples/graphql-request/package.json
- examples/graphql-request/public/robots.txt
- examples/graphql-request/src/App.js
- examples/graphql-request/src/app.css
- examples/graphql-request/src/components/Header.js
- examples/graphql-request/src/index.js
- examples/graphql-request/src/pages/404.js
- examples/graphql-request/src/pages/About.js
- examples/graphql-request/src/pages/Home.js
- examples/graphql-request/src/pages/Post.js
- examples/graphql-request/static.config.js
Static blog example using `graphql-request` and GraphCMS as data source.
> graphql-request example

- README.md
This is the website that I've built for my latest project: https://github.com/hql287/Manta
> Added a website built with React Static.

- src/links.js
`<Link to="mailto:me@example.com">` and `<Link to="//cdn.example.com/file.zip">` will now also work.
> More protocols caught in links

- src/links.js
[Discussion](https://github.com/nozzle/react-static/pull/231#issuecomment-350627282)
> Warn when active used on NavLink incorrectly

- examples/sass/static.config.js
> Add the plugin to the sass example

- README.md
- examples/custom-routing/README.md
Emphasize consequences of using custom routing: `static.config.js` will generate pages and data anyway.
> Alert on routing synchronization

- src/links.js
react-router documentation had this functionality missing.
https://github.com/ReactTraining/react-router/pull/5799
> Pass DOM props through in links, fixup f19d13454

- src/static.js
Fixed bug that Helmet's HTML attributes do not pass.
> Fix typo in HtmlWithMeta function params

- src/index.d.ts
> Overwrite Router export from react-router

- src/index.d.ts
> Export Routes component on react-static-routes

- README.md
I have not tested these features in full, but React-Static seems to support hot code reloading for React Components and CSS as well as LAN access from other devices out of the box. Would be good to emphasise these features in the README.md, as they are crucial for many developers.
> Add documentation for hot code reloading and LAN access

- examples/typescript/index.d.ts
- examples/typescript/package.json
- examples/typescript/src/App.tsx
- examples/typescript/src/app.css
- examples/typescript/src/containers/404.tsx
- examples/typescript/src/containers/About.tsx
- examples/typescript/src/containers/Blog.tsx
- examples/typescript/src/containers/Home.tsx
- examples/typescript/src/containers/Post.tsx
- examples/typescript/src/index.tsx
- examples/typescript/src/path-alias-example/component.tsx
- examples/typescript/src/types.ts
- examples/typescript/static.config.js
- examples/typescript/tsconfig.json
> Add entry for tsx component

- examples/apollo-redux/README.md
(write your answer here)
2. `node -v`:
Then, specify:
1. 
2. 
3. 
> fix a typo

- README.md
Reverts nozzle/react-static#321
> Revert "Fix link to staticconfig.js documentation"

- docs/api.md
> Missing parenthesis

- docs/api.md
Fixed a broken anchor link for #routes-react-static-routes
> Broken anchor fix

- docs/api.md
Fixed a few semicolons and closing div tags.
> Example code typos

- src/index.js
(write your answer here)
2. `node -v`:
Then, specify:
1. 
2. 
3. 
> make `pathname` work on `to` object prop

- src/index.js
Yes
1. `react-static -v`: 5.1.6
2. `node -v`: 9.5.0
3. `yarn --version or npm -v`: 1.3.2
Then, specify:
1. Operating system: Windows
2. Browser and version (if relevant): IE11
1. react-static build
2. Load the site on IE11
3. 
Navigation should work
Navigation doesn't work
N/A
> Fixes #357 IE11 (fallsback to document.body.appendChild)

- src/index.d.ts
I just updated type definitions so it corresponds with v.5.1.7
> Update type definitons

- README.md
I just added a new entry to the list of sites made with react-static
> Add Cryptagon to sites made with React-Static

- README.md
Added a link to the Algolia example.
> README.md to include Algolia

- README.md
I added Typetalk site to the list of sites made with react-static.
React Static is really cool! Thank you!!!
> Add Typetalk to sites made with React-Static

- README.md
(write your answer here)
2. `node -v`:
Then, specify:
1. 
2. 
3. 
> Added Built With Site

- examples/netlifycms/README.md
- Fixed "Deploy to Netlify" button (removed .git at end of url). 
- Wrote detailed instructions on setting-up and using RS with NetlifyCMS.
> edit readme and deploy url

- docs/concepts.md
Unnecessary paren was found in the docs, small fix! 😄
> docs: remove paren

- examples/netlifycms/.babelrc
- examples/netlifycms/.eslintrc.js
- examples/netlifycms/gitignore
- examples/netlifycms/package.json
- examples/netlifycms/public/admin/config.yml
- examples/netlifycms/src/containers/Post.js
- examples/netlifycms/src/posts/2018-02-18-sample-post-1.md
- examples/netlifycms/src/posts/2018-02-18-sample-post-2.md
- examples/netlifycms/src/posts/2018-02-18-sample-post-3.md
- examples/netlifycms/static.config.js
- using public_folder fixes need to rewrite image URLs.
- using react-markdown avoids dangerouslySetInnerHTML which fixes
content disappearing on reload of blog posts.
- add missing dot files
See corresponding PR in example repo: tsgriff/react-static-netlifycms#1
> fix: netlify cms example

- README.md
Added a simple artist portfolio site to sites built with React Static.
> Update README.md Sites built with

- README.md
* Add PSD Wizard to sites made by react-static at Readme.md :)
> add PSD Wizard to sites built with react-static

- bin/react-static-build
- bin/react-static-create
- bin/react-static-start
bin files had async in them.  this meant that we need to 
upgrade the engines file in package.json and require everyone to be node v8 or higher
or
use promises in bin
> (fix) - use promise so no need to upgrade node version

- src/static/RootComponents.js
Bootstrap and HTML5 boilerplate projects did it:
https://github.com/twbs/bootstrap/pull/17793
https://github.com/h5bp/html5-boilerplate/pull/1984
> Add shrink-to-fit=no to <meta viewport>

- examples/material-ui/static.config.js
Materil → Material
No
2. `node -v`:
Then, specify:
1.  Create a material-ui project
2. Typo is in static.config.js
3. 
> Minor typo correction

- examples/netlifycms/netlify.toml
Netlify detect lock file, it use yarn when yarn.lock exists. I think it is better to use npm to run script as it built-in
No
2. `node -v`:
Then, specify:
1. 
2. 
3. 
> change command to npm

- examples/less-antdesign/tsconfig.json
Forgot to update this example also for this PR: https://github.com/nozzle/react-static/pull/480#issuecomment-374284450
> TypeScript: Excluded node_modules in tsconfig.json

- docs/api.md
> Fix api.md spelling typos

- src/client/components/Router.js
yes
1. `react-static -v`: ^5.5.0
2. `node -v`: 9.5.0
3. `yarn --version or npm -v`: 1.3.2
Then, specify:
1. Operating system: mac osx
1.  create blog post or page with Japanese slug ex.(/jp/blog/日本語)
2. navigate to page by clicking link
3. try to reload page
https://github.com/nozzle/react-static/issues/508
Page should reload the same and page with English slug
Page quickly flashes, then goes to 404
> feature(multi-language slug): decode href for language support

- src/client/methods.js
> Comment refers to routeInfo.js instead of routeInfo.json

- docs/api.md
- docs/concepts.md
> Fix api.md and concepts.md spelling typos

- README.md
New site built with React Static: [NYC Vintage Map](https://nycvintagemap.com)
> Update README.md Sites Built with React-Static: NYC Vintage Map

- src/utils/shared.js
> Fixed invalid pathname

- README.md
This pull request adds my website [danwebb.co](https://danwebb.co) to the list of "Sites Built with React-Static".  I built the site with React Static and use markdown files as per my pull request #562 
I also updated some of the structure by starting with my [React static starter](https://github.com/DanWebb/React-Static-Starter) code but feel like it's too opinionated to be added as an example in the repo.
> Add Dan Webb personal website to the sites built list

- README.md
Added another site utilizing React-Static.
readme.md
To help support the project by adding a high profile brand.
Just a markdown change.
> added another site that uses react-static

- docs/config.md
- Fixed disablerouteinfowarning and disablerouteprefixing links in `config.md` and added a little more information about the disableRoutePrefixing flag
> fixed links and added more description to disableRoutePrefixing

- examples/markdown/package.json
Update jdown to a version with fixes for windows users for the markdown example 
- #581 
- https://github.com/DanWebb/jdown/issues/2
- https://github.com/DanWebb/jdown/issues/3
> Update jdown to use ^0.3.0

- src/static/index.js
Use `renderToStaticMarkup` instead of `renderToString` when rendering the `Document` component.
See above.
This prevents comments from being rendered in the title tag when using variables rendered as text nodes. These comments would flash while the page was loading and would show up in site preview (e.g., chats, possibly search results).
The following:
```jsx
import React from 'react'
import { Head } from 'react-static'
const first = 'foo';
const second = 'foo';
const third = 'foo';
export default () => (
<div>
<Head>
<title>{first} | {second} | {third}</title>
</Head>
</div>
);
```
Outputs the following:
```html
<!DOCTYPE html>
<html lang="en-US" data-reactroot="">
<head>
<title data-react-helmet="true">foo | foo | foo</title>
</head>
```
With these changes, we get the following:
```html …
```
> Render document to static markup.

- README.md
Add Neighborhoodwatch.io to sites built with react-static list
> Updated list of sites built with React Static

- README.md
Choosing to remove this site as it is clouding our analytics data. No hard feelings!
Please email support@tioh.co if you need extra confirmation, but please check https://github.com/nozzle/react-static/pull/389 
to see the initial PR adding it to the list.
> Removing website I added

- src/static/__tests__/__snapshots__/getConfig.test.js.snap
- src/static/__tests__/getConfig.test.js
- src/static/components/BodyWithMeta.js
- src/static/components/HeadWithMeta.js
- src/static/components/HtmlWithMeta.js
- src/static/components/__tests__/BodyWithMeta.test.js
- src/static/components/__tests__/HeadWithMeta.test.js
- src/static/components/__tests__/HtmlWithMeta.test.js
- src/static/components/__tests__/__snapshots__/BodyWithMeta.test.js.snap
- src/static/components/__tests__/__snapshots__/HeadWithMeta.test.js.snap
- src/static/components/__tests__/__snapshots__/HtmlWithMeta.test.js.snap
- src/static/getConfig.js
- src/static/index.js
This PR pulls out the components from the static index file and adds some snapshot test around them. It breaks up the functions in the static index file. 
Also, add comments to recurseCreateNormalizedRoute as it is a complicated function.
> Break up static index to be more modular

- README.md
I'm a huge fan of React Static and built basically every new site with it :)
Add a line to the README
React Static is awesome. I may write blog posts soon about my experience.
> Add BlockAce to Site's Built with React-Static

- README.md
added my personal site, https://lukehaas.me, to the list of sites built with react-static
List is short, better to have more examples.
> add site to list of sites built with react-static

- src/static/index.js
```
TypeError: Cannot read property 'length' of undefined
- index.js:211 _callee10$
.../[react-static]/src/static/index.js:211:49
```
Error building
> Reference the routes array..

- docs/concepts.md
Two small fixes to the "core concepts" section in the docs
> Fix typos in the docs

- babel-preset.js
- package.json
- src/static/components/HeadWithMeta.js
- src/utils/index.js
- src/utils/progress.js
- yarn.lock
react-static with many pages can take a while for certain operations like exporting html. On CI servers, the progress bar will not show since TTY doesn't work. This PR will add a fallback that shows rolling progress.
This PR uses steps of 5% but we can change this.
> allow progress in non-TTY (and fix testing)

- docs/config.md
- docs/node-api.md
> Fixed broken link

- README.md
Added a website to the list.
Just a readme update.
n/a
It's a good example of a company website built with react-static.
None of these apply
> Added new website to the list of 'made with react static'

- src/static/generateRoutes.js
- src/static/index.js
- src/static/webpack/rules/jsLoader.js
Reverts nozzle/react-static#707
> Revert "WIP: fix building app to some folder outside app-root"

- docs/concepts.md
The non-static router example was lining to a GitHub 404 page. Changed it to link to the correct file.
Error in documentation link.
> Fix non-static router example link in concepts.md

- README.md
Hi! Not sure if this is the right way to do this but we're excited to tell you that we've just relaunched or site after rebuilding it w/ React-Static! It's now super-fast and developing w/ it was 💪 and we couldn't be happier!
This PR/edit adds our site to your "Sites Built with React-Static" list.
> New site using React-Static added to the list

- README.md
React Static is awesome, thanks for it 🎉🎉🎉
http://smash-tier-list.com ([source](https://github.com/desko27/smash-tier-list))
This is an Open Source Tier List application that covers all characters in Super Smash Bros game series. I've been working at this side project these days, it's not 100% ready but I thought it would be nice to share it here, if it's ok for you.
> Add smash-tier-list.com to sites built

- src/utils/chunkBuilder.js
fixes an case in my previously introduced feature
> remove possible leading path separator

- README.md
> Add hackduke.org to sites built

- README.md
> Update Examples & Templates in Readme.md

- docs/browser.md
- docs/plugins.md
> Typos in Docs

- README.md
add camp.rhms.cf with source to 'made with react-static' section
> add camp.rhms.cf with source to 'made with react-static' section

- README.md
Adding Goodly as I recently migrated it from gatsby
> Add Goodly

- docs/concepts.md
Changed `React` to `React Static`.
> Fix typo in concepts docs

- README.md
> re-add Fullstack HQ to sites made with react-static

- docs/guides/animated-routes.md
Fixed a typo in the guide
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
> Fixed typo in package name

- README.md
> fix plugin link in Readme

- README.md
I'd like to add a website to the list of made with react-static.
> Add a website to the list

- docs/concepts.md
Docs guides links were broken. I fixed them.
> Update links to guides to make them work

- docs/plugins/README.md
Add link to react-static-plugin-favicons. I'm not sure if "assets" is an appropriate category, so I'm open to other suggestions.
It links to a new plugin I just created.
> Add link to react-static-plugin-favicons

- docs/plugins/README.md
- packages/react-static-plugin-less/.babelrc
- packages/react-static-plugin-less/.gitignore
- packages/react-static-plugin-less/README.md
- packages/react-static-plugin-less/package.json
- packages/react-static-plugin-less/src/node.api.js
- yarn.lock
Adds SSR and general support for LESS
> Add plugin: react-static-plugin-less

- docs/plugins/README.md
> Update plugin documentation to be more concise.

- docs/guides/apollo.md
Added guide for Apollo
This guide explains how to use Apollo to fetch data both client-side and at build-time, explaining also the advantages of both and why sometimes it is sensible to query data both at build-time and on the client.
- [ x ] Added apollo.md file
Have the guide for Apollo
- [ x ] New feature (non-breaking change which adds functionality)
> Create Apollo guide

- docs/components.md
> Minor change of prop type description

- README.md
- docs/concepts.md
- packages/react-static/templates/README.md
Each change is a separate commit and there are few enough to just read the commit messages
Update to several README.md and added a new one for templates
Improvments to docs
> A few doc updates after discussion on Spectrum

- packages/react-static/templates/typescript/.babelrc
The TypeScript template did not properly setup Babel to parse
static.config.js.
Include `.babelrc` for the TypeScript template as well.
It fixes #980.
> Make sure Babel parses static.config.js

- docs/config.md
The documentation has 404 link. I found the proper target (I suppose). Please follow with this as you please.
> Broken link in documentation

- docs/components.md
Removes typos and improves consistency of headings for `components.md`.
> Improve components.md

- docs/guides/incremental-builds.md
Fixes a few typos, including one incorrect negative
Typos are bad. They confuse readers and make searching difficult.
> Fix typos in incremental-builds readme

- docs/plugins/node-api.md
Missing closing bracket in example code
- [x ] Changed documentation
Update example code in the documentation so it compiles.
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
> Missing closing bracket in example code

- docs/config.md
Update plugin documentation link
- [ x] Fix documentation
Broken link in the documentation.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
> Update plugin documentation link

- packages/react-static-plugin-mdx/src/node.api.js
- packages/react-static/src/browser/index.js
https://github.com/nozzle/react-static/issues/1008
> Fix prefetching issues

- packages/react-static/src/browser/components/Routes.js
* Cache wrapped 404 component
* Prevent wrapping of non-404 components
* Remove function creation from render method
Fixes #974
> Fix remount of component on history update

- packages/react-static/src/static/webpack/index.js
Make sure shared data is injected correctly by the dev server.
> Fix shared data in dev mode

- packages/react-static/src/static/buildHTML.js
Log thread count instead of core count
It was incorrectly logging cores instead of threads
> Log threads not cores from export

- docs/config.md
Document `paths.buildArtifacts`.
> Update config.md: Document `paths.buildArtifacts`

- README.md
Adds Starbucks Sites Built, with link to source.
> Updates README.md with Starbucks Careers site

- README.md
Updating site list in README with new site.
> Add Amplify Credit Union to sites in README

- packages/react-static/src/browser/components/RouteData.js
I'm sorry, that last PR needed a bit more testing...
> Fix fetching route data for non-preloaded routes

- packages/react-static/src/browser/utils/__tests__/shared.test.js
- packages/react-static/src/browser/utils/index.js
* Use `location.href` as base URL
* Mock `document.location` in unit tests
> Simplify prefetchable route detection

- packages/react-static/templates/basic/package.json
This fixes #1066 and potentially #990.
Context explained in #1066
See #1066
> Remove --single flag from serve in basic template

- packages/react-static/templates/blank/src/App.js
Case fix for app.css import in blank template
- [ x] Changed code
Fix typo.
> Fixed case of app.css import in blank template

- packages/react-static-plugin-mdx/src/node.api.js
in node.api.js:
config => afterGetConfig
V7 changed the node plugin api
> react-static-plugin-mdx: adopt latest plugin api

- packages/react-static-plugin-sitemap/src/__test__/__snapshots__/buildXML.test.js.snap
- packages/react-static-plugin-sitemap/src/buildXML.js
> Removes invalid closing `</xml>` tag

- packages/react-static-plugin-sitemap/src/__test__/__snapshots__/buildXML.test.js.snap
- packages/react-static-plugin-sitemap/src/buildXML.js
> Minifies output of sitemap plugin

- packages/react-static-plugin-source-filesystem/README.md
> Update this Readme w/ info about importing path.

- packages/react-static/src/static/exportRoute.js
> Remove console.log used for debugging

- docs/guides/aws-lambda.md
> Working configuration for Lambda.

- docs/concepts.md
Just fixed broken link to api.md from concepts.md
> Fix broken link in concepts.md

- docs/api.md
- docs/concepts.md
- docs/config.md
Use `template:` instead of `component:` for static routes in every `.md` documentation files
Having an up-to-date documentation
> Update route declaration documentations

- README.md
added personal site, I am a proud react-static user
> Update README.md - added personal site

- packages/react-static/package.json
- packages/react-static/templates/blank/yarn.lock
- packages/react-static/templates/stress-test/yarn.lock
- packages/react-static/templates/typescript/yarn.lock
react-helmet@5.2.1 fixes the issue described in #1119. I bumped its version everywhere.
Fixes #1119.
> Bump react-helmet to v5.2.1 to fix #1119

- docs/plugins/README.md
- packages/react-static-plugin-evergreen/.babelrc
- packages/react-static-plugin-evergreen/.gitignore
- packages/react-static-plugin-evergreen/README.md
- packages/react-static-plugin-evergreen/package.json
- packages/react-static-plugin-evergreen/src/node.api.js
Following #1186, here is a PR to add SSR support for [evergreen](https://github.com/segmentio/evergreen)
More details in #1186
> Register react-static-plugin-evergreen plugin

- docs/guides/styled-components.md
Got a few questions about people wanting to use with styled components and there was no guide for it yet.
- Added guide file
Make it more easy for people to use react-static with their preferred css solutions.
- [*] New feature (non-breaking change which adds functionality)
- [*] I have updated the documentation accordingly
> Styled components guide added

- docs/config.md
Just a documentation update.
Just a documentation update.
Closes #1202
> Add documentation for config.entry

- README.md
added source code link for my site (fourthdrive.com) ☺
> Update README.md - added source code for my personal site

- docs/config.md
This PR adds a mention of the `useSiteData` hook in the config.md
Formatted the document to include the mention, the component and the HOC
Using SiteData was confusing at first as I didn't know the hook existed too
> Mention `useSiteData` hook in the config.md

- packages/react-static/templates/typescript/yarn.lock
fix following issue
[Bug] TypeScript Template does not Build or Run #1163
TypeScript template provide  react-static v7.0.5.
> react-static: ^7.0.0 => 7.0.5 
But when I install and run it, I get an error. 
But if I  update to 7.1.0 you can run without errors 
https://github.com/nozzle/react-static/issues/1163#issuecomment-488172133
upgrade react-static version to v7.1.0(latest)
> fix(template): TypeScript Template does not Build or Run #1163

- CHANGELOG.md
- packages/react-static/package.json
- packages/react-static/templates/stress-test/package.json
- packages/react-static/templates/stress-test/yarn.lock
- packages/react-static/templates/typescript/package.json
- packages/react-static/templates/typescript/yarn.lock
- yarn.lock
Bump react-hot-loader to v4.12.10
Solves https://github.com/react-static/react-static/issues/1267
> Bump react-hot-loader to 4.12.10

- packages/react-static/src/browser/index.d.ts
Fix TypeScript's type error.
See: #1299
addPrefetchExcludes raises errors.
```
$ yarn start
yarn run v1.17.3
$ react-static start
Starting Development Server...
Building Routes...
Importing routes from directory...
[✓] Routes Built (0.4s)
Building Templates...
[✓] Templates Built
Bundling Application...
Starting type checking service...
Using 1 worker with 2048MB memory limit
Fetching Site Data...
[✓] Site Data Downloaded
Error: ✖ ｢wdm｣: 
ERROR in /tmp/my-static-site/src/App.tsx
ERROR in /tmp/my-static-site/src/App.tsx(9,21):
TS2345: Argument of type 'string[]' is not assignable to parameter of type '
string | RegExp'.
Type 'string[]' is not assignable to type 'string'.
Error: ✖ ｢wdm｣: 
ERROR in /tmp/my-static-site/src/App.tsx
ERROR in /tmp/my-static-site/src/App.tsx(9,21):
TS2345: …
```
> Fix: addPrefetchExcludes's type error

- packages/react-static/src/index.d.ts
- fixes a typo in the typescript typings
> fix: witeSiteData -> withSiteData

- packages/react-static/bin/react-static
Updated the usage information.
Closes #1314
> fixup usage info

- docs/concepts.md
The old link points to documentation about build notifications (this is evident by looking at the URL redirect: https://docs.netlify.com/site-deploys/notifications/), not about build hooks to start a build. This PR updates the link.
> Updates webhook example link for Netlify

- CHANGELOG.md
- docs/config.md
- packages/react-static/src/browser/index.js
- packages/react-static/src/static/getConfig.js
Possible to choose whether log on production is `on` or `off`
It closes #1271
> Fix #1271 - optional log on production

- packages/react-static-plugin-styled-components/src/node.api.js
Fixed a typo: `extraced` -> `extracted`
Just fixed a typo 😸
> Fixed typo

- README.md
Removed tannerlinsley.com from 'Sites Built with React-Static' list.
tannerlinsley.com is now build with Next.js
https://github.com/tannerlinsley/tannerlinsley.com/blob/master/README.md
> Built with Next.js serverless
https://github.com/tannerlinsley/tannerlinsley.com/commit/3a94ed60ce730697f99793ebef9abebbce76e772
It is sad but the site should be removed from 'Sites Built with React-Static' list.
> Removed tannerlinsley.com from 'Sites Built with React-Static' list

- CHANGELOG.md
- packages/react-static-plugin-jss/package.json
- packages/react-static-plugin-jss/src/node.api.js
Basically change the imports as mentioned in #1266
> update plugin for react-jss v10+

- docs/api.md
Change link Prefetch to usePrefetch and update anchor links of usePrefetch and prefetch
> Fix prefetch links

- docs/guides/styled-components.md
> added the missing styled import

- README.md
> remove staticgen from sites using section as they use gatsby now

- packages/react-static-plugin-sass/src/node.api.js
> Fix HMR configuration in sass plugin

- docs/guides/animated-routes.md
The example doesn't work in the current version of react static. The suggested changes do.
> Updating Animated Routes Docs

- packages/react-static/templates/basic/package.json
Fixes https://github.com/react-static/react-static/issues/1420
> add eslint-plugin-react-hooks as devDependency

- docs/concepts.md
A minor addition to add tiiny.host as part of the documentation under hosting options.
Tiiny Host also appears on [Gatsby's documentation](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-to-tiiny-host.md)
Gives users another very easy and free hosting option
> Update documentation to include tiiny.host for hosting

- CHANGELOG.md
- packages/react-static/src/browser/components/Routes.js
- packages/react-static/src/browser/utils/index.js
- packages/react-static/src/static/webpack/runDevServer.js
> 🤘🏽 Release/7.4.0

- packages/react-static-plugin-styled-components/README.md
Link to styled-components was wrong. According to plugin source, it uses `styled-components`, not emotion’s `styled`.
> docs(styled-components): Fix project link

- CHANGELOG.md
- packages/react-static-plugin-mdx/.gitignore
- packages/react-static-plugin-mdx/README.md
- packages/react-static-plugin-mdx/package.json
- packages/react-static-plugin-mdx/src/fm-loader.js
- packages/react-static-plugin-mdx/src/node.api.js
- packages/react-static/src/Suspense.js
- yarn.lock
The plugin can now pull out frontmatter metadata when processing markdown files.
To demonstrate, create a basic `react-static` site (`react-static create --template basic`). Install this plugin and add the following to `static.config.js`'s `plugins` array:
```javascript
[
'react-static-plugin-mdx',
{ parseFrontMatter: true }
],
```
Create the following markdown file in `src/markdown/about.md`
```markdown
---
title: Awesome!
---
```
Change the template's `about.js` to
```javascript
import about, { frontMatter } from '../markdown/about.md';
console.log(frontMatter); // Will output { title: 'Awesome!' }
export default about; // A React component for (<h1>A new 'About' page</h1>)
```
You should see a new 'About' page and the developer console will output the frontmatter.
To be backward …
> Add frontmatter support to the MDX plugin

- CHANGELOG.md
- packages/react-static/src/utils/binHelper.js
fixes https://github.com/react-static/react-static/issues/1508
> fix: console error behaviour with no arguments

- packages/react-static-plugin-typescript/package.json
- packages/react-static-plugin-typescript/src/node.api.js
- yarn.lock
- Update plugin version to latest
- Upgrade plugin configuration
- This is a breaking change, if users are using anything less than: Node.js 10, Webpack 4, TypeScript 2.7
- Keeping up-to-date with package versions
- Remove dependency on chokidar 2
> Update fork-ts-checker-webpack-plugin to latest version

- CHANGELOG.md
- packages/react-static/package.json
- yarn.lock
Upgrade React Helmet to newest version
It fixes an issue with warnings for NullComponent
> Upgrade react-helmet to 6.1.0

- README.md
Add EarningsCall to the list of sites that use react-static.
> Add EarningsCall to the site list.

- README.md
The readme discussions link didn't actually lead to discussions
> fix Readme discussions link
