react-static/react-static

README.md

Links was missing a `#` at the beginning

README: Fix link to #configuration-staticconfigjs

---

README.md

Just the same missing `#` for the `Project setup` section like in #23

Fix README link to project setup

---

README.md
examples/basic/static.config.js
examples/custom-routing/static.config.js
examples/glamorous/static.config.js
examples/styled-components/static.config.js
src/DefaultHtml.js

`react-static` uses an UTF-8 based magnification process for its build. To ensure those files are interpreted properly by browsers, we should make sure all the HTML-Heads do have the required `<meta charSet="UTF-8" />` included to prevent surprisingly breaking code.
- Added `<meta charSet="UTF-8" />` to template and baseline files
- Added `<meta charSet="UTF-8" />` to readme code samples
This closes https://github.com/nozzle/react-static/issues/46

Add "Charset UTF-8" to HTML-Head in code and readme.

---

src/commands/index.js

This allow to use:
```
$ react-static -v
1.4.1
$ react-static --version
1.4.1
```

Add an option to output the version in the CLI

---

README.md

Fixing a typo in the documentation I just wrote... It's time for bed.

Fix typo in PrefetchWhenSeen documentation

---

README.md

Readme still states `These docs are for version 1.x.x.`. Change to `3.x.x`. While I think about it, with @calvinrbnspiess changes we need to jump another major version anyhow. And master is not on npm yet? @next points to version 2 alpha.

Update Readme ver to 3.x.x to prevent confusion

---

src/webpack/webpack.config.prod.js

Loaders, such as `cssLoader` depend on the availability of the stage property to determine if we are in stage === "dev" — it will be undefined otherwise during build.
Yes. For loaders, the stage property needs always to be defined to do build phase testing.
(write your answer here)
1. `react-static -v`: master
2. `node -v`: v8.2.1
3. `yarn --version`: 1.2.1
1. Try to build an example from master
Should build.
```bash
=> Bundling App...
TypeError: Cannot read property 'stage' of undefined
at _default (/Users/worker/development/react-static-typescript-exploration/node_modules/react-static/lib/webpack/rules/cssLoader.js:22:19)
at _default 
```

Incl. stage property in rules for prod (undefined)

---

src/webpack.js
src/webpack/rules/cssLoader.js

Post-Css Loader only has one instance in the webpack build process if it is used multiple times. The options are only set once. To be able to use post-css to its fullest, enable sourceMaps so path-throughs work properly when other style loaders use post-css.
I.e. this is necessary to have a working less loader without dublicating the default cssLoader.

Set sourceMap for Style-Loader Instances

---

examples/typescript/static.config.js
src/webpack.js
src/webpack/rules/cssLoader.js

Since the format was changed, the exclude is undefined from the rules array. Leading babel to crash by processing `node_modules` and probably the rest of the internet if we let it... 😄

FIX TypeScript Example: Babel exclude undefined

---

src/configServer.js

I'm using hotel to get things running without port/address collision, then I need to pass a port by to get things working as expected while developing my application.
I'm an experienced angular developer in a starting react journey in the company I work for, I learned NextJS and had just found React Static hours ago as a similar (but it really sounds better) SSR framework, by the way.
Thnx, keep rocking. Best regards.

Using PORT from process.env instead, if it exists

---

src/webpack.js

This fixes https://github.com/nozzle/react-static/issues/101 for me. With this in place, I can now get the webpack config for my `.storybook/webpack.config.js` from the `webpackConfig` function exported from `react-static/webpack` .

Export webpack config function

---

src/webpack/webpack.config.prod.js

`react-static start` is working great after the path refactor, but `react-static build` crashed because the `config` is not passed properly to the rules function.

Fix webpack production config destructuring

---

src/static.js

This bug is detailed in #138. This is the simplest fix I could think of for this bug. It ensures that `Template` is a valid React element before trying to render it and returns `undefined` otherwise.
```
-> % react-static -v && node -v && npm -v
4.0.1
v8.3.0
5.3.0
```
Operating system: macOS Sierra 10.12.6
1. Run `react-static create`
2. Choose `basic` template (it should be a bug with any template, but I haven't confirmed)
3. Remove this from `static.config.js`:
```
{
is404: true,
component: 'src/containers/404',
},
```
4. Run `npm run build`
I expected the `build` command to run without errors
The `build` command threw an error

Ensure Template is a valid React element before trying to render it

---

package.json
src/index.d.ts

Bundles full TypeScript support. Since React-Static is just a thin layer around existing well typed libraries, we are relaying the type information accordingly (react-router, react-helmet).
This enables TypeScript / WebStorm users to use autocomplete and propper reference to the react-static library.
Since this is a declaration file that doesn't engage with any implementations (just a declaration), this does not effect code in anyway.

Typings for React-Static for full TypeScript Support

---

examples/custom-routing/README.md

This PR fixes a small typo and allows the example's README to properly render.

Fix Markdown syntax error

---

.npmignore

In #140 the project added TypeScript typings (yeay!). But after installing 4.1.0 I am unable to find the typings file in my `node_modules`, because [they are ignored as a part of `src`](https://github.com/nozzle/react-static/blob/81fa589470afe84a4a623a4c97f505da86705f7f/.npmignore#L7).
@D1no @tannerlinsley

Unignore typings for production bundles, fixup #140

---

src/static.js

The template imports are currently hardcoded to be imported one folder up. This PR makes the imports dynamic, so that the potential `paths` given by the user in `static.config.js` can be general. Closes https://github.com/nozzle/react-static/issues/154.

Make template imports dynamic

---

README.md

Npm already versions the docs. So there is no need to have the extra burdon to update it again inside of the docs... and potentially forget about it. This bugged me for a while.
No.

Update Readme: Clarify docs versioning 

---

src/commands/index.js

Extensions not getting through to webpack as they are blocked by the Babel preprocessor.
Yes 
See: https://github.com/nozzle/react-static/issues/171

Add .md & .yaml to Extension whitelist

---

src/commands/index.js
src/static.js

Yes
See #178 
Any version
1. Create a route prop with a string containing `<script></script>`
2. Build the static site
3. Open the static page in any browser
The page would render correctly
The browser stops parsing the route props generated by react-static as soon as it encounters the character sequence `</script>`, causing the rest of the script to incorrectly be interpreted as document markup.
Break the generated JSON string and rejoin with `+` operator to avoid the browser parsing it as a closing script tag

Escape script tags in routeData (#178)

---

src/index.js

Yes
1. `react-static -v`: 4.2.3
2. `node -v`: 8.9.0
3. `yarn --version`: 1.3.2
1. Create a new `basic` example with `react-static create`.
2. Start the dev server with `yarn start` and navigate to `http://localhost:3000/blog/post/1/` and refresh.
Gets the routes from `/__react-static__/getRoutes` 
Gets the routes from `blog/post/1/__react-static__/getroutes`
https://github.com/nozzle/react-static/issues/176

Make the getRoutes url absolute

---

src/index.js

This PR adds a fallback to the `PrefetchWhenSeen` component to make it work properly in Edge, [since it doesn't support the `isIntersecting` property](https://github.com/w3c/IntersectionObserver/issues/211).
`PrefetchWhenSeen` differs from `Prefetch` in that it has an element in the DOM. This PR adds a `className` prop so that this element can be styled.

Add Edge fallback and className to PrefetchWhenSeen

---

src/commands/index.js
src/utils.js

Yes
1. `react-static -v`: 4.3.0
2. `node -v`: 8.9.0
3. `yarn --version`: 1.3.2
1. Add `paths: { devDist: 'local' }` to `static.config.js`
2. Start the dev server with `yarn start`
Creates a `local` folder and uses that instead of `dist` 
Uses the `dist` folder
`process.env.NODE_ENV` is not set properly, so the `process.env.NODE_ENV === 'development'` check when giving `paths.DIST` a value is not working as intended. Explicitly giving it a value on `start` and `build` works great.
The `HTML_TEMPLATE` path also had to be made dynamic, and all the files were now created in the correct folder.
https://github.com/nozzle/react-static/issues/181

Set NODE_ENV on start/build, use distPath for html template

---

src/static.js

Fixes https://github.com/nozzle/react-static/issues/184
1. `react-static -v`: 4.3.2
2. `node -v`: 9.2.0
3. `yarn --version or npm -v`: yarn 1.3.2
Then, specify:
1. Operating system: Windows 10
1. Run example on Windows (I used the styled-components one)
Run without error. 
[path.resolve(config.paths.ROOT, template),](https://github.com/nozzle/react-static/blob/da68e23609742a38cf22b92eef07d343f2af44be/src/static.js#L241) is returning OS specific paths. On Windows they contain backslashes instead of slashes. To fix this, all backslashes need to be replaced with slashes, because even on Windows the import paths have forward slashes.
`

Fix path for imports on Windows

---

examples/less-antdesign/package.json

The `^` does not work with npm version tags. This fixes it.

less-antdesign: Fix antd scope in package.json

---

README.md

No
I noticed a few people were looking for this and the only answer is somewhere in the hour-long youtube video. Seems like something useful to add.

Added class example for route props to readme

---

.npmignore

.esm-cache is a huge folder (~25mb) which results in the react-static package being ~35mb.
Is this folder necessary for the published package?
It is already being ignored via [.gitignore](https://github.com/nozzle/react-static/blob/master/.gitignore#L20). 
1. `react-static -v`: 4.3.4
2. `node -v`: 8.9.1
3. `yarn --version or npm -v`: yarn 1.3.2
4. Operating system: macOS
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

Add .esm-cache to the .npmignore

---

examples/apollo-redux/src/index.js
examples/apollo/src/index.js
examples/basic/src/index.js
examples/blank/src/index.js
examples/cordova/src/index.js
examples/custom-routing/src/index.js
examples/dynamic-imports/src/index.js
examples/glamorous/src/index.js
examples/less-antdesign/src/index.js
examples/redux/src/index.js
examples/styled-components/src/index.js
examples/typescript/src/index.js

This PR changes `ReactDOM.hydrate` to `ReactDOM.render` in dev mode in all the examples, so the user doesn't get `Warning: Expected server HTML to contain a matching <div> in <div>.`, as outlined by @mattyfresh in https://github.com/nozzle/react-static/issues/144.

Use ReactDOM.render instead of ReactDOM.hydrate in dev

---

examples/graphql-request/package.json
examples/graphql-request/src/pages/Post.js

So it turns out the `dangerouslySetInnerHTML` was working because the post's `content` field was rich text. It has been converted to markdown in default `Blog` template and in the project that the example is using atm.
I've added `react-markdown` to the example and removed `dangerouslySetInnerHTML` to reflect the rich text -> markdown change.

Update graphql-request example to use react-markdown

---

README.md

Correct the phrasing of "react-component" to "PATH of a react-component" relative to this issue: [#220](https://github.com/nozzle/react-static/issues/220)

Re-phrasing

---

src/index.js
src/links.js

Fix non-routing Link component usages (#210)

---

src/commands/build.js
src/commands/index.js
src/commands/start.js
src/static.js

Allows configuring builds from the command line by forwarding all additional CLI arguments to `getSiteProps()`. 
The parameter to `getSiteProps` is an object that now has a `cliArguments` property which is an array of strings that followed the command `build|serve|create` on the command line

Pass additional CLI arguments through to getSiteProps()

---

src/index.js

Adds `shouldPrefetch` function that is intended to be used in conjunction with `isPrefetched` when firing wrapped routing methods.
This avoids calling `setLoading(true)` and `setLoading(false)` and subsequently calling any Router subscribers if there is no data to be loaded for requested path.
The issue I was having with the current logic implementation was that routes that do not have any props defined within `static.config.js`, regardless of site props being used, would still trigger the Router loading subscribers. 
If you are using these subscribers to show a loading overlay, for example, you can see this flash momentarily as the state changes. As no request is actually fired for routes with no data, I presume the loading state should not be set?
Routes with props/using `getRouteProps` …

Add shouldPrefetch() method to avoid setting loading state unnecessarily

---

src/webpack/index.js

When a file has a space in it, we need to encode the URI we listen on otherwise these routes are unaccesible from the browser. This only affected the dev server.

Handle routes with spaces

---

src/index.js

Yes. https://github.com/nozzle/react-static/issues/254
1. `react-static -v`: 4.7.1
2. `node -v`: 8.9.0
3. `yarn --version`: 1.3.2
1. Create a new `basic` example with `react-static create`
2. Use the same component with the `getRouteProps` HOC for more than one route (like e.g. https://github.com/nozzle/react-static/issues/254)
3. Start the dev server and navigate between these routes that have the same component
Should get the route props when the route change
The loading spinner appears and `Warning: getRouteProps could not find any props for route: /<your_route_with_the_same_component>.` is shown in the console.
There is currently no logic to fetch the route props when the `match` changes for the same component. This results in `loaded` being set to `true`, but `initialProps` not being …

Prefetch when route for getRouteProps component change

---

src/static.js

react-static 4.7.0...4.8.2 are still broken in Node 6, with what we discussed in #256 is BC breakage. This fixes it.

Fix Node 6 support

---

examples/sass/static.config.js

The bug reason is that `sass-loader' expects `includePaths` option to be an array:
https://github.com/webpack-contrib/sass-loader/blob/master/lib/normalizeOptions.js#L73
1. `react-static -v`: 4.8.3
2. `node -v`: v8.1.2
3. `yarn --version or npm -v`: 5.5.1
Then, specify:
1. run `react-static create`
2. pick a `sass` template
3. run `npm run build`
Here is a console log:
```
ERROR in ./src/app.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: options.includePaths.push is not a function
at normalizeOptions (/home/mrurenko/projects/saas-test/node_modules/sass-loader/lib/normalizeOptions.js:73:26)
at …
```

fix 'includePaths' config for 'sass-loader'

---

README.md

Added a **Note** to the README about not using `ReactDOM.hydrate` when using `preact: true` config option.
This stumped me for a bit until I saw the [note in the CHANGELOG](https://github.com/nozzle/react-static/blob/master/CHANGELOG.md#480) about making this switch and then looking at the `preact` example.
I thought this should be added to the README as it may catch out other people too, particularly those who are adding the `preact` option to and existing react-static app based on a different template.

Added note about ReactDOM render method when using preact

---

package.json
src/static.js

1. `react-static -v`: 4.9.0-beta.5
2. `node -v`: v8.9.4
3. `yarn --version`: 1.3.2
Then, specify:
1. Operating system: Windows
The build should produce a `react-static-routes.js` file containing a path to each template that works across operating systems.
Error after building:
```bash
./dist/react-static-routes.js
Module not found: Can't resolve '..srcpagesHome' in 'C:\path\to\project\dist'
```

Use slash paths for templates consistently across OSes

---

README.md

Yes
The environment details are irrelevant and therefore I'm leaving them blank
2. `node -v`:
Then, specify:
1. Open the documentation `https://www.npmjs.com/package/react-static`
2. Click on `Configuration (static.config.js)` under documentation
3. Nothing happens
It should move to the `Configuration (static.config.js)` section on the page
Nothing Happens when clicked on that link (the Url changes to something but the page does not scroll to the right element)
When clicked on the following `Configuration (static.config.js)`
Should move to the following `Configuration (static.config.js)`
The above screenshots should be clear enough

Fix link to staticconfig.js documentation

---

package.json
src/commands/create.js
yarn.lock

Addresses #323
* Through having a custom template option and using https://github.com/flipxfx/download-git-repo we can support templates from GitHub, BitBucket, and GitLab. It requires 'owner/repo' format and for the repo to be public.
* I pulled `basic` out to this repo https://github.com/mjsisley/react-static-template-basic to test manually
At the moment, it blows up with errors in the following cases:
* A string that doesn't follow this format `owner/repo` is passed by the user (`download-git-repo` doesn't error gracefully)
* There is a network error via `download-git-repo`
* Adding command line args as an option is tangential, so won't do that here.
* It would be ideal to support arbitrary URLs (s3 or something?), local paths, and npm packages. Not doing that now.

[CLI] Add custom option for template that takes a remote public repo to `react-static create`

---

examples/styled-components/static.config.js

Wrong function called in static.config.js for styled-components demo to get site data, changed from `withSiteData` to `getSiteData`

styled-components config siteData functional call fix

---

docs/api.md

The information for devServer config object is repeated twice in the API Reference docs. 
I also would personally would like to see the default port 3000 on the example - helps greatly when searching how to change this setting. Alternative option is to mention something in the line of `Change from default port 3000` in a comment line.

API Reference: Remove duplicate devServer

---

docs/api.md

An example component render is missing a closing tag.

api.md closing tag fix

---

src/index.d.ts

Fixes
```
[ts] Module ''react-static'' has no exported member 'withSiteData'.
```
when trying to
```js
import { withSiteData } from 'react-static'
```
Although other type definitions could use a little love as well, IMO this is pretty important to add considering the error shows up immediately after initializing a new project with the [official TypeScript template](https://github.com/nozzle/react-static/tree/master/examples/typescript).

Add missing typing for withSiteData

---

.babelrc

The react hot loader babel plugin [already checks the environment it is running in](https://github.com/gaearon/react-hot-loader/blob/572e803fde186d2f2d59754f404c1d9094ca750a/babel.js). As of this PR the plugin does nothing in production, though it is conceivable that it could do something in the future (e.g., removing the `hot` HOC) and therefore it's probably best to just leave it in the standard `plugins` configuration.

Move react-hot-loader/babel out of env.

---

src/index.js

This patch replaces a prime with an apostrophe (see https://webdesignledger.com/common-typography-mistakes-apostrophes-versus-quotation-marks/). Normally I'd consider this as "not worth the time", but because a prime is used, GitHub's syntax highlighting gets confused and the code is illegible.
----

Use an apostrophe rather than a prime

---

docs/api.md
src/static/getConfig.js
src/static/index.js
src/static/webpack/rules/cssLoader.js
src/static/webpack/webpack.config.prod.js

Two config options were added:
1. `extractCssChunks` - replaces default `ExtractTextPlugin` with `ExtractCssChunks`. It enables automatic CSS splitting into separate files by routes as well as dynamic components (usign `react-universal-component`). More information about the [plugin](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin) and [why it is useful as a part of CSS delivery optimisation](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin#what-about-glamorous-styled-components-styled-jsx-aphrodite-etc). Defaults to `false`.
2. `inlineCss`. By using extractCssChunks option and putting code splitting at appropriate places, your page related CSS file can be minimal. This option allows you to inline your page related CSS in order to speed up your application …

Add options to use extractCssChunks and inlineCss

---

src/utils/binHelper.js

Referencing `woff2` files in your project source (including files in node_modules) causes the build to fail. Fixes issue https://github.com/nozzle/react-static/issues/456
Yes.
1. `react-static -v`: 5.5.11
2. `node -v`: v8.9.0
3. `yarn --version or npm -v`: yarn 1.3.2
Then, specify:
1. Operating system: macOS Sierra 10.12.6
1. Add `woff2` font files to your project source and reference them
2. Run `yarn build`
Successful build and processing of font files.
https://github.com/nozzle/react-static/issues/456
```
$ react-static build
=> Copying public directory...
=> [✓] Public directory copied: 1.602ms
=> Building Routes...
=> [✓] Routes Built: 271.802ms
=> Bundling App...
=> [✓] App Bundled: 6799.957ms
=> Exporting Routes... …
```

Add 'woff2' to ignoredExtensions array

---

package-lock.json
src/client/methods.js

First commit allows for better logging when getRouteInfo can't find routeInfo.
Second commit disables prefetch when path is undefined (e.g., when updating only the query string).

Better logging for getRouteInfo(). No prefetch for undefined routes. Fixes #459

---

src/utils/scrollTo.js

Whatever the reason behind the scroll getting to the location too early,
if we do not abort, we will continue doing no-op `window.scroll` operations
for the rest of duration. This means that the user in the meantime can not scroll.
Fixes #449.

Prevent scroll from being stuck

---

src/client/components/RouterScroller.js

In my codebase that I did not manage to reduce for a demonstration,
RAF would delay the scrollTo call so much that the browser would have already instanly scrolled us to the correct location.
As a result the scrollTo would then be a no-op.
Instead, we now attempt to scroll as soon as possible, synchronously,
and fall back on RAF if that did not work.
Fixup efbaa1618. Fixes #449. Related to #460, but does not make that irrelevant.

Fix corner case of hash scroll not happening

---

package.json
src/static/index.js
test/minimal-website/static.config.js
yarn.lock

Yes
1. `react-static -v`: 5.5.14
2. `node -v`: v8.9.4
3. `yarn --version or npm -v`: yarn 1.2.1
Operating system: macOS
Browser and version (if relevant): Chrome
1. Use specific UTF-8 characters in getData
2. Load the URL page by browser reload (redirect by AJAX works well)
3. RS shows 404, because there is an error about unparsable JS code.
Page should load well with browser refresh and show correct data.
404

Fix server-side rendering of data with UTF-8 special characters

---

examples/less-antdesign/package.json
examples/less-antdesign/static.config.js
examples/typescript/package.json

fixes #367 
fixes #318 
The typescript example was outdated. `ts-loader` is **fixed to v3.x** until react-static ventures into webpack 4.
The antdesign example **would neither start nor build anymore**. Reasons were the changed HMR system and an internal change of how flexible the antd less files are now.
1. Try to update TypeScript example and build
2. Try to run or build a less-antdesign example
3. (Please Note: less-antdesign is based on the TypeScript Example)
Both examples should run and build.
Both examples don't run and build.
- Both Examples have been updated to its latest dependencies
- Both Examples have been checked to properly
- run
- Hot Module Replace with vanilla JS and TypeScript use
- build
- serve

Example Maintenance: TypeScript & fix Less-AntDesign

---

bin/react-static-build
bin/react-static-start

682d35a9c930386133997b86d603b9be85495628 broke the ability to use --config to point to a static.config.js file.
Non-boolean options should include a `<value>` segment in the option commander definition.

Fixed --config arguments

---

package.json
src/commands/build.js
yarn.lock

Before:
After:
I would like to see this also in watch mode.

Using pretty-error package for nicer error reporting during build

---

src/static/index.js

When build fails, I am often missing the URL and component which failed. This enhances the original Error message with info about those things.

Show URL and component path of error during build

---

examples/typescript/tsconfig.json

I'm pretty sure `node_modules` should be excluded - this was preventing my dev environment to load React-specific types correctly.
[According to the official doc](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html):
> The `"exclude"` property defaults to excluding the `node_modules`, `bower_components`, `jspm_packages` and `<outDir>` directories when not specified.
My `code` tag isn't using type definitions from `@type/react`:
My `code` tag uses type definitions from `@type/react`:

TypeScript: Excluded node_modules in tsconfig.json

---

examples/material-ui/package.json
examples/material-ui/src/App.js

Yes.
The Material UI example cannot currently be used due to:
`Module not found: Can't resolve 'material-ui/Reboot'`
This is a recent breaking change in Material UI v1.0.0-beta.37:
https://github.com/mui-org/material-ui/pull/10605
https://github.com/mui-org/material-ui/releases
1. `react-static -v`: 5.6.1 
2. `node -v`: 8.10.0
3. `yarn --version or npm -v`: 1.3.2
4. Operating system: macOS 10.13.3
1. Create a new React Static site using the `material-ui` template
2. Run `yarn start` (or `yarn build`)
The app should be served at http://localhost:3000
The node process dies with `Module not found: Can't resolve 'material-ui/Reboot'`

Update Material UI example to use recently renamed CssBaseline component

---

src/static/webpack/index.js

Closes https://github.com/nozzle/react-static/issues/479

Keep user's devServer.watchOptions when running dev server

---

docs/api.md

Change from `noIndex` to `noindex`.
Fix indent on `dev: Boolean`.
Related warning when running `build`:
https://github.com/nozzle/react-static/blob/master/src/static/getConfig.js#L122I
No. A small doc fix.

Fix api docs: getConfig noindex

---

src/commands/build.js

Fix #500. Also removes React warning about unminified React in production.
I’m not sure you want this as the best solution to #500. After all, this makes it so that `build --debug` is now one step more different from production. At the same time it was super strange that `--debug` does not show, you know, debug information. Finally, maybe we think that non-minification already makes this build far enough from production, so might as well not set NODE_ENV.
This is a judgement call, and I am not sure about this solution, thus this PR is separate from the issue.

Disable NODE_ENV=production in build --debug

---

src/static/generateRoutes.js

Attempt to fix #487.
The likely cause is the dynamic generation of the component which does not pass React reconciliation check. [An article by Huy Nguyen](https://www.huy-nguyen.com/2017-01-avoid-unnecessary-remounting-react/) explains it in more detail. In our code it’s in `generateRoutes`:
https://github.com/nozzle/react-static/blob/dfd927c5c24977e16d13debe807872fca2fe2e0e/src/static/generateRoutes.js#L82-L86
dfd927c5c2 may have been an attempt to fix it, but it does not help.
Currently this workaround in my code works:
```js
const workAroundRender = reactStaticProps => {
const render = props => {
const Comp = reactStaticProps.getComponentForPath(props.location.pathname);
return Comp && Comp(props);
};
return <Route path="*" render={render} />;
};
<Routes render={workAroundRender} /> …
```

Fix losing internal state in components on hash navigation

---

src/commands/start.js
src/static/webpack/index.js

Serve directly from the public directory rather than copying it's contents ahead of time.  Makes it much easier to tweak files and get instant feedback.  (admin/config.yml for Netlify CMS in my case)
Closes #484

Serve directly from public.

---

src/client/components/Router.js

When first loading an app in dev mode there was a request to `/_react-static_/routeinfo/undefined`. This fixes the issue.
fixes #523

Fix 404s on homepage at first load

---

package.json

This issue causes react static to break at startup.
since it's very simple I just skipped the whole description.

Fixes a missing dependency that is required in binHelper

---

src/client/components/RouterScroller.js

This fixes the undesirable behaviour described in #551.

Do not scroll-to-top on initial page load

---

.eslintrc.js
docs/components.md
package.json
setupTests.js
src/client/components/ErrorWrapper/ErrorCatcher.js
src/client/components/ErrorWrapper/ErrorUI.js
src/client/components/ErrorWrapper/__tests__/ErrorCatcher.test.js
src/client/components/ErrorWrapper/__tests__/__snapshots__/ErrorCatcher.test.js.snap
src/client/components/ErrorWrapper/__tests__/__snapshots__/index.test.js.snap
src/client/components/ErrorWrapper/__tests__/index.test.js
src/client/components/ErrorWrapper/index.js
src/client/components/Router.js
src/index.d.ts
yarn.lock

This pull request decouples error handling and UI  from the `<Router />` and moves it into the `<ErrorWrapper />` . Introduces additional prop on the `<Router />`, `showErrorsInProduction` which when set to `true` to enable the debug/error page in production. Defaults to `false`, error page does not appear in production.
This pull request fixes #553 and introduces some tests arounds the changes.

Fixes issue with error page showing in production

---

src/static/webpack/rules/jsLoader.js

`production` is not one of the valid stages, according to [docs](https://github.com/nozzle/react-static/blob/5fe177934381da6a79e15d4c5d96ef5d77a6a35d/docs/config.md#webpack):
> `args.stage` is a string of either `prod`, `dev` or `node`, denoting which stage react-static is building for.

Use correct build stage name in jsLoader

---

docs/node-api.md

The current example of the `rebuildRoutes` method in the [node api docs](https://react-static.js.org/node-api#rebuildroutes) gives an error: "TypeError: paths.map is not a function". I haven't dug in to investigate why this error is caused but it seems to be caused by the parameters chokidar passes to the function.
Save time for other people who follow the docs example and will probably encounter the error.

Fix error caused by rebuild routes docs example

---

docs/components.md

Couldn’t find `getTemplateForPath` mentioned anywhere in the code, so I’m assuming this is an error.

Fix function name in Components docs

---

docs/config.md
src/client/components/Router.js
src/client/methods.js
src/static/getConfig.js

Disabling the route prefix will allow the usage of a base URL that will apply to most resource GET requests but not history and route URL requests.
An example use case would be `mysite.com/us/en/blog` which would request for `/us/en/blog/index.html` and `/us/en/blog/routeInfo.json`. But allowing other root resources to be at a different baseUrl such as `my-blog`. Loading the `mysite.com/us/en/blog` would request for `/my-blog/bootstrap.981e38c5.js`
https://github.com/nozzle/react-static/issues/571
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.

Added new configuration option 'disableRoutePrefixing'

---

src/client/methods.js
src/static/webpack/webpack.config.prod.js

Follow up fix to https://github.com/nozzle/react-static/pull/572
If the `config.disableRoutePrefixing` flag is set then requests for `routeInfo.json` must also ignore baseRoute prefixing to ensure the correct file is retrieved. This file is stored directly next to the route so the prefixing must mirror that of routes.

Checking config.disableRoutePrefixing to get correct routeInfo

---

src/static/webpack/rules/cssLoader.js
src/static/webpack/webpack.config.prod.js

Currently in 5.8.1, CSS files are getting extracted in both node and prod stages. This results in two identical CSS files.
This PR removes `ExtractCssChunks` and  `ExtractTextPlugin` when in the node stage.
Run `yarn run text-sample-build` and notice it generates two CSS files with identical content.

Don't extract CSS in webpack during node stage

---

src/client/methods.js
src/static/index.js

When the `config.disableRoutePrefixing` flag is used the `basePath` should not be used to preface path links. The sitemap should mirror the behavior.
- [ x ] Bug fix (non-breaking change which fixes an issue)

Correct URL in sitemap when `config.disableRoutePrefixing` is used

---

src/client/components/RouteData.js

This is more like a work-a-round. The root-cause however is the prop `is404` being `undefined` here.
This does hover resolve my issue with the built 404 page.

A possible fix for #539

---

src/client/components/Router.js
src/client/methods.js
src/static/index.js

fixes #593 
We are setting `process.env.REACT_STATIC_DISABLE_ROUTE_PREFIXING` to a boolean value here: https://github.com/nozzle/react-static/blob/master/src/static/getConfig.js#L153
But node converts this to a string by default.
Thus this code does not work as expected: https://github.com/nozzle/react-static/blob/master/src/client/methods.js#L84
`process.env.REACT_STATIC_DISABLE_ROUTE_PREFIXING` is "false" which evaluates to true

Compare `process.env` variables as strings rather than booleans.

---

package.json

Test files shouldn't be included in the built `/lib` directory. 
This PR ignores `**/__tests__/*` when running `yarn build` or `yarn start`.

Don't include test files when creating a build

---

examples/less-antdesign/package.json
examples/less-antdesign/src/App.tsx
examples/less-antdesign/static.config.js
examples/sass/package-lock.json
examples/sass/static.config.js
examples/tailwindcss/static.config.js

fixes #588
This is the same issue that was fixed with https://github.com/nozzle/react-static/pull/574 where we don't want to extract CSS files in both "prod" and "node" stages. This would result in two duplicate CSS files.
During the node stage we don't include the ExtractTextPlugin. This example was breaking because it was trying to use that plugin during the node stage.

Fix examples that override webpack css-loaders

---

src/static/index.js

If `config.disableRoutePrefixing` is enabled, we should not be replacing `href`s from HTML. 
https://react-static.js.org/docs/config#disablerouteprefixing

Don't replace hrefs if disable route prefixing

---

testExamplesBuild.js

Adds a script to build all the examples in an automated manner.
testBuildsExample.js is a script that builds all the examples.
It is possible that changes to the react-static library can cause some of the examples that are shipped with the library to stop working. There is no easy way for a developer to check if their changes are breaking any of the templates that react-static supports. This script builds every example and if any example fails to build it prints out the error and exits with an error code.
TODO:
- integrate this with travis

Adds Automated building of all examples

---

examples/algolia/src/App.js
examples/animated-routes/src/App.js
examples/apollo-redux/src/App.js
examples/apollo/src/App.js
examples/basic-prismic/src/App.js
examples/basic/src/App.js
examples/cordova/src/App.js
examples/custom-routing/src/App.js
examples/dynamic-imports/src/App.js
examples/firebase-auth/src/App.js
examples/glamorous/src/App.js
examples/markdown/src/App.js
examples/netlifycms/src/App.js
examples/non-static-routing/src/App.js
examples/pagination/src/App.js
examples/preact/src/App.js
examples/redux/src/App.js
examples/sass/src/App.js
examples/styled-components/src/App.js
examples/styled-jsx/src/App.js
examples/typescript/src/App.tsx

Update Example templates
The example nav routes call `<Link to="/">Home</Link>`, which causes the routes to match root AND all child pages. This fixes this so Nav correctly states aria-current states for the current navigation items across many examples.
Making it easier to spin up sample projects

Use exact root routes in examples Nav

---

src/static/getConfig.js

Adds logging of compiler errors during requiring of config file (like `static.config.js`)
When `static.config.js` contains any compiler errors causing `require(configPath).default` to fail, `react-static build` fails with a rather unhelpful error message (since it tries to continues with an empty configuration)
``` TypeError: Cannot read property 'DIST' of undefined```
This makes debugging errors in `static.config.js` hard.

Report errors when building configuration

---

src/client/methods.js

prevent REACT_STATIC_CACHE_BUST from getting discarded by pathJoin
pathJoin removes the get parameters from the path and thus prevents process.env.REACT_STATIC_CACHE_BUST from having any effect. This change pulls the cache busting param outside of pathJoin and makes sure it survives into the build.
This is needed for cache busting of routeInfo.json files. Without this, no method exists for cache busting of those files.

fix cache busting for routeInfo.json via route param

---

src/static/__tests__/__snapshots__/buildXML.test.js.snap
src/static/__tests__/buildXML.test.js
src/static/buildXML.js

I had some issues with Google rejecting my sitemap.xml because it contained invalid XML. Some XML characters need te be escaped while generating sitemap.xml (e.g. `&`)
This should fix that.

Sitemap.xml may contain invalid characters

---

src/static/index.js

Fix issue with lots of routes where config cannot be stringified.
Fixes https://github.com/nozzle/react-static/issues/658

Fix issue with lots of routes where config cannot be stringified

---

src/static/getConfig.js

Hey, I encountered an error when trying to provide react-static CLI (v.5.9.7) with custom config path. Here is a one line PR to fix this.
Fixes an error (details below) when running any command with custom config file, eg.: `react-static --config ./custom.static.config.js start`.
Tested also with deep paths from package.json, so running `react-static --config ./example-com/static.config.js start` will now also work.
```
> react-static --config ./static.config.js start
Error: Cannot find module './static.config.js'
- loader.js:594 Function.Module._resolveFilename
internal/modules/cjs/loader.js:594:15
- loader.js:520 Function.Module._load
internal/modules/cjs/loader.js:520:25
- loader.js:650 Module.require
internal/modules/cjs/loader.js:650:17
- helpers.js:20 require …
```

Fix unresolved config with custom path

---

docs/config.md
src/commands/export.js
src/static/__mocks__/defaultConfigProduction.mock.js
src/static/getConfig.js
src/static/webpack/index.js

Add config temp path option, create client-stats.json and bundle-environment.json in temp path instead of dist.
https://github.com/nozzle/react-static/issues/664

Add temp path config and use it for non-dist files in build

---

examples/typescript/src/App.tsx

Since `react-static-routes` is auto generated, it should be ignored by tslint when importingl.
Since tslint is often used alongside typescript this PR aims to ease adoption by newcomers to not run into linting errors and by accident installing the `react-static-routes` package.

Ignore unknown dependency react-static-routes in typescript example

---

babel-preset.js

Set babel runtime module name to `@babel/runtime` using the new `@babel` namespace. See https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html#modulename
Fixes #670.

Set babel runtime module name to @babel/runtime

---

examples/typescript/src/index.tsx

Removed double render from typescript example, I guess this was a copy & paste mistake.
If only one render is required, we should only do one.

Removed double render from typescript example

---

src/client/components/Router.js

When using `window.location.href` we need to url decode it before it can be used as a path for finding template IDs. Otherwise we end up with url encoded paths that can't be reconciled with the build phase were they are url decoded.
Fixes #652. See `bootstrapRouteInfo` for same logic.

Added url decode before using window.location.href as path

---

examples/typescript/static.config.js

`config.extensions` is set to `['.js', '.jsx']` by default. This needs to be extended with `.ts` and `.tsx` to allow auto-discovery of typescript pages.
Currently typescript pages are not being discovered in the example thus leading to errors when using `react-static start`:
```
Error: Could not find a route for the "index" page of your site! This is required. Please create a page or specify a route and template for this page.
```

Extend extensions in typescript config example so that pages are discovered

---

src/static/generateRoutes.js

react-router uses path-to-regexp, which will not recognize `*`
Read
https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x
=> `No wildcard asterisk (*) - use parameters instead ((.*))`
But leaving the path away in react-router `Route` will effectively match all routes.
Please publish if you accept this change :) I'm living on the edge!

[Bugfix] Remove path="*" since its broken with latest dependencies

---

babel-preset.js
src/static/webpack/rules/jsLoader.js
src/static/webpack/webpack.config.dev.js
src/static/webpack/webpack.config.prod.js

Fixes https://github.com/nozzle/react-static/issues/683
This changes the default configuration for babel passed from babel-loader such that the `modules` [option](https://babeljs.io/docs/en/next/babel-preset-env.html#modules) is set to `false`, as well as some other changes to webpack configuration to ensure that ES modules are used instead of CommonJS modules wherever possible.
See https://github.com/nozzle/react-static/issues/683
* When the user imports an identifier from an ES6 module that is not exported, webpack throws an error. Previously, there was no error, and instead at runtime the imported variable would be `undefined`. This includes both user code (provided they use ES6 imports/exports), and packages (provided the package provides ES modules in the `module` field of …

Configure babel to not transpile ES6 modules to CommonJS

---

src/static/components/HeadWithMeta.js
src/static/components/__tests__/__snapshots__/HeadWithMeta.test.js.snap

This ensures that the CSS included in the static.config Document head element comes before the component-created CSS.
Fixes [#622](https://github.com/nozzle/react-static/issues/622)
If users have materialize or other CSS <link> they've declared in the static.config Document() <head> element, those <link>'s will now appear above the component-level CSS that is created by react-static. This fixes the issue in 622 where component-level CSS is being overridden by CSS defined in static.config Document() <head> element. This bug only occurred during react-static build command, not react-static start.
[See Issue #622](https://github.com/nozzle/react-static/issues/622)
This change is required to ensure CSS libraries like materialize that are included in static.config Document <head> do not …

Fixes CSS Sorting in Issue 622

---

CONTRIBUTING.md

Replace `yarn watch` with `yarn start` according to change in package.json
`yarn watch` in no longer available in package.json scripts

`yarn start` in CONTRIBUTING.md

---

src/commands/create.js

Instead of @latest version, check version in react-static's package.json and use it in yarn/npm commands to add `react-static` dependency.
Fixes #728 
See #728

Use react-static package version in create command

---

CHANGELOG.md

Fix one letter typo in `changelog.md`. Should be self-explanatory. I can elaborate further if necessary.

FIX typo in changelog.md

---

examples/netlifycms/public/admin/index.html

Hi Tanner! just tried the netlifycms template out and it failed when i was authenticated. did some digging and found you were still using 1.0 and the problem went away when i bumped the version to 2.1 (latest). so here's a one line PR.
netlifycms template doesnt work anymore without this upgrade

bump netlifycms version to 2.1

---

package.json
yarn.lock

[CHORE]: Updating RUC (react-universal-component)
Should get rid of those "critical dependency is a expression" warnings you see in webpack 4.16
<3 <3

[CHORE]: Updating RUC (react-universal-component)

---

README.md

I added a website that uses react-static under the hood to the "Sites Built"-section: [anagrams.io](https://anagrams.io).
Anagrams.io tries to be the best anagram generator ever built, react-static helped me to make it even faster and SEO friendly. 
It adds a website that's different than all the other "Sites Built" websites and shows that SVG generation and animations are no problem at all.

Add anagrams.io to sites built

---

src/static/webpack/rules/jsLoader.js

`babel.config.js` doesn't have a period in front.
https://babeljs.io/docs/en/config-files#project-wide-configuration
My project uses a `babel.config.js` file.

Correct spelling of babel.config.js

---

src/static/webpack/index.js

[This commit](https://github.com/nozzle/react-static/commit/58fee0247a87d44e75a5f3ccf8ca5a1337e8fa69#diff-aca7fc77f9db0ace2a7962f2e30c4085L57) changed the `getPluginHooks` function which now only includes `config.plugins` array and no longer includes `config.webpack`.
https://github.com/nozzle/react-static/blob/v6/docs/plugins.md#webpack-functionfunction
We should still be able to configure webpack without having to create a plugin.

Make sure to run the config.webpack hook

---

README.md

I noticed that the **Sites Built with React-Static** section of the README included [HeadlessCMS.org](https://headlesscms.org) but not [StaticGen.com](https://www.staticgen.com), which was [recently "migrate[d] over to React Static using headlesscms repo as a template"](https://github.com/netlify/staticgen/pull/370). That seems like a major endorsement of React-Static as a static site generator (almost on par with the React documentation site using Gatsby) and should not go unnoticed.
See Description.

Add StaticGen.com to the list of sites built with React-Static

---

babel-preset-external.js
package.json
src/static/webpack/rules/index.js
src/static/webpack/rules/jsLoader.js
src/static/webpack/rules/jsLoaderExternal.js
src/utils/chunkBuilder.js
yarn.lock

as a general exclude on node_modules doesnt seem to be a good idea, we compile them too (but with a bare minimum of features). the idea is inspired by CRA https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/webpack.config.prod.js#L313-L353
separate babel loaders for SRC and NODE_MODULES
to be able to use external ESM

compile node_modules with bare minimum too

---

docs/config.md
src/static/__mocks__/defaultConfigDevelopment.mock.js
src/static/__mocks__/defaultConfigProduction.mock.js
src/static/getConfig.js
src/static/webpack/webpack.config.prod.js

Bugfix for issue: https://github.com/nozzle/react-static/issues/755
This PR enables sourcemap generation for javascript chunks in production builds
- added `generateSourceMaps` option to the config
- fix issue https://github.com/nozzle/react-static/issues/755
See: https://github.com/nozzle/react-static/issues/755

Bugfix: generate sourcemaps for production builds

---

src/static/webpack/rules/jsLoader.js

somehow the `tmp` paths on OSX behave weird, so we simple change the static files to a regex on the filename

make the static files location more flexible

---

examples/material-ui/package.json

Material-UI removed their dependency to `react-jss` in `v3.2.0` so it no longer gets pulled in automatically.
I added `react-jss` dependency to material-ui's template
This PR solves #818

Add missing dependency to material-ui template

---

package.json
src/static/webpack/webpack.config.prod.js
yarn.lock

Fixes `Unexpected token: punc ())` errors during build.
1. Commit automatic 'integrity' info from yarn 1.10
2. Use updated UglifyJsPlugin for create-react-app compatibility
- Fixes `Unexpected token: punc ())` errors during build
- See discussions for details:
- https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104#issuecomment-358646531
- https://github.com/webpack/webpack/issues/5858#issuecomment-338430720
- See also [UglifyjsWebpackPlugin docs](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/)
Note: I've verified this change on my own production app, but I haven't tested much beyond that. You can see the build logs after the change [here](https://travis-ci.org/cooperka/neuro-name/builds/444617571).

Use updated UglifyJsPlugin for create-react-app compatibility

---

packages/react-static-example-blank/src/App.js
packages/react-static-example-contentful/src/index.js
packages/react-static-example-previous-next-navigation/src/index.js
packages/react-static-test-site-large/src/index.js
packages/react-static/src/static/webpack/rules/index.js
packages/react-static/src/static/webpack/rules/jsLoaderExternal.js
packages/react-static/src/utils/__tests__/chunkBuilder.test.js
www/src/App.js
yarn.lock

Per https://github.com/nozzle/react-static/pull/829#issuecomment-431940885, I went to apply the changes from #829 to branch v6, but it looks like the plugin is already configured [here](https://github.com/nozzle/react-static/blob/v6/packages/react-static/src/static/webpack/webpack.config.prod.js#L89). I applied the automatic yarn changes, at least :tropical_drink:

Update yarn integrity + prettier

---

examples/documentation/static.config.js

Fix the incorrect watched directory configured in `example/documentation`
Recently I tried to use the `documentation` template, found that the doc folder being watched do not point correctly at the template's own doc folder. This might be confusing for starters. 
Tested in my local mac that after this fixing, the template project created by `react-static create` with `documentation` type will be correctly watching the project `doc` directory and rebuild nicely  in development.

fix: example documentation watching incorrect dir

---

examples/material-ui/package.json
examples/material-ui/src/containers/404.js
examples/material-ui/src/containers/About.js
examples/material-ui/src/containers/Blog.js
examples/material-ui/src/containers/Home.js
examples/material-ui/src/containers/Post.js
examples/material-ui/src/theme.js
examples/material-ui/static.config.js

Updated material-ui example to use latest core version. Closes #806
- removed deprecated typography usage: https://material-ui.com/style/typography/#strategies
- add react and react-dom to deps
- Removed private imports from jss
Typography is deprecated which can cause some confusion when installing the the example. I know @krvajal claimed it but the issue has been open for 3 weeks, is considered chore and I already used those changes when experimenting with react-static.
- Do you have tests for examples?

Update material-ui example

---

.travis.yml

test-sample-build assumes that react-static has been built locally
Travis CI started failing after this commit: https://github.com/nozzle/react-static/commit/fb126d9d9632752cfadc0ba68d64268b165accfe#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L30

fix(travis-ci): build react-static before testing

---

packages/react-static/src/commands/start.js

The `--config` CLI argument's currently broken in v6. The [exported `start` command](https://github.com/nozzle/react-static/blob/c270bc879cc49fd42bd448a33bd337116385db3f/packages/react-static/src/commands/start.js#L16) takes in `configPath` as its argument, but the start bin [still passes `config`](https://github.com/nozzle/react-static/blob/c270bc879cc49fd42bd448a33bd337116385db3f/packages/react-static/bin/react-static-start#L17).
This issue: https://github.com/nozzle/react-static/issues/848

fix: Accept config arg in CLI start command

---

src/index.d.ts

Fix existing typings & add react-static/node typing
- Current typing has wrong type, it occurs type error(following error).
> JSX element type 'RouteData' does not have any construct or call signatures.
- too many `any` exist in current typing.
I refer https://react-static.js.org/docs/ to write specific types & types of `react-static/node`.
This typing is tested with typescript 3.0.3

Fix typings & add react-static/node typing

---

packages/react-static/package.json
packages/react-static/src/static/getRoutes/getRoutesFromPages.js
packages/react-static/src/utils/binHelper.js

See https://github.com/babel/babel/issues/9032
I'm not sure if the ignore path is necessary. But I know it will cause issues in its current form. I'm not able to start any react-static example without this change.

Fix issues with windows paths

---

packages/react-static-plugin-sass/src/node.api.js

fix `css-loader` 2.0 version changes.
The `minimize`option was removed. I add the minimize option (like before) for older versions. at some point we can drop this backport.
https://github.com/webpack-contrib/css-loader/issues/863

fix css-loader 2.0 version breaks (removed minimize option)

---

packages/react-static/src/static/generateTemplates.js

Tries to fix #877.
The solution is to convert the value of `REACT_STATIC_UNIVERSAL_PATH` from Windows-style path separators to Unix-style using the `.split('\\').join('/')` trick as has been done in some other files.
(I say try, because trying to build the repo results in the following warning, and no build results:)
```
PS C:\koodia\react-static> yarn build
yarn run v1.7.0
$ lerna run 'build' --ignore react-static-example-*
lerna notice cli v3.5.1
lerna info filter [ '!react-static-example-*' ]
lerna success run No packages found with the lifecycle script ''build''
Done in 0.61s.
``` 
(This is with latest versions of Node, Yarn and Lerna)
Might fix #877. I've been unable to run this PR, so I don't know if there are some other issues preventing Windows builds from working.

Fix Windows path handling in generateTemplates.js

---

packages/react-static/src/browser/index.js
packages/react-static/src/browser/utils/index.js

we do some checks now if the link should be prefetched et all.
a lot of avoidable `routeInfo.json` requests are dropped which results in `404` responses (to e.g. external urls or `javascript:` links)

less aggressive prefetching (check if link should be prefetched)

---

docs/plugins.md

The key is actually `jsLoaderExt`, rather than `jsLoaderExternal`, as can be seen here:
https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/rules/index.js#L8
Alternatively, the key could be changed there, but that would be a breaking change. Your call :)
The documentation was incorrect w.r.t. the actual code.

Fix name of `jsLoaderExt` in the plugins API

---

README.md

I created react-static-plugin-typescript; this PR adds it to the list of plugins.
Note: on Twitter I mentioned wanting to give this a more thorough run-through on my own project, but since I'm [stuck on upgrading that](https://spectrum.chat/react-static/general/how-to-use-reach-router-with-react-static-v6~c0b4658e-bd3c-4d15-93da-8391a491b9dc) I figured I'd submit this anyway, since it otherwise appears to work fine.
It tells people who want to use TypeScript which plugin they can use.

Add react-static-plugin-typescript to plugin list

---

packages/react-static/src/index.d.ts

I'm not sure if there's any other prop in Root.
Also, I'm not sure if type RootProps  should be where it is or if it should be exported at all.

Add Root Component typescript types

---

packages/react-static/package.json
packages/react-static/src/static/__mocks__/configWithPluginWithOptions.mock.js
packages/react-static/src/static/__tests__/getConfig.test.js
packages/react-static/src/static/getConfig.js

Options can be provided to plugins by passing an array instead of
the plugin name, with as first element the plugin name, and an
options object as the second argument. However, this array was
destructured as follows:
originalLocation = originalLocation[0]
options = originalLocation[1] || {}
Because the first line overwrote `originalLocation` with the name
of the plugin, the second line would actually assign the second
character of that name to `options`, rather than the second element
of the array. Switching them around fixes that.
Plugins could not actually receive options. This PR fixes that.
Note that I am not too satisfied with the way I structured the tests, especially the part where I modified the actual code to set a plug-in's name to `mock-plugin` when in the test environment (as …

Make sure plugin options are passed on to plugins

---

docs/config.md

Adds documentation for the `renderToElement` hook, which I only found in the CHANGELOG for v6. Note that I'm not sure whether this is complete, e.g. whether `meta` is passed to this function as well.
It was undocumented.

Document the `renderToElement` hook

---

packages/react-static-plugin-css-modules/src/node.api.js

CSS Loader 2.0 disables CSS Modules by default, so in the node build config, css module support is disabled and no mappings are exported. The `options` object needs to remain present in the node config, albeit with the addition of `exportOnlyLocals: true`.
- Added `...options` to css-loader options during node build stage.
With css-loader v2 builds break without this change.
**No open issue for this**

fix css-loader 2.0 support

---

docs/guides/animated-routes.md

The example does not work with the latest version of react-sprint. See react-spring `Transition` usage http://react-spring.surge.sh/transition#/red The PR fixes the issue and the animation works properly. 
There is still an issue with `withRouteData` & `withSiteData` when navigating as the route that is on its way out looses its data due to a re-render. I was not able to fix that yet.
Fixed animated-routes example code to work with latest react-spring version
The animated-routes example did not work with the latest version of react-sprint.

Update animated-routes example to animate properly.

---

packages/react-static/src/browser/components/Root.js

This adds a wrapper component for the default `ReachRouter` that conditionally adds the `ServerLocation` component when the route is being statically rendered.
Fixes #945. Reach Router requires the `ServerLocation` component to provide the route location information during static rendering. See: https://reach.tech/router/server-rendering

Add ServerLocation during static render

---

packages/react-static/src/static/RootComponents.js

`[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5.`
i think its safe to set the max scale to 5

fix lighthouse Accessibility

---

packages/react-static/src/commands/create.js

Adding \" on path name solves the problem
Wrapped path name with " ", that way the project can be created in folders named like "my project" without breaking the application
https://github.com/nozzle/react-static/issues/951

fix project name with spaces on 'react-static create' #951

---

README.md

Spotted a minor typo in `README.md` while reading through React Static docs

Fixed typo in README, tuturials -> tutorials

---

packages/react-static/src/browser/index.js

I've added one more check before prefetch is being done so that it can be disabled easily.
This feature was working fine in React-Static v5, but in v6 there's a new router it stopped working.
By adding `prefetch="false"` to a `<Link>` component we can prevent React-Static from prefetching this route.
Some documentation has to be added, but I wasn't sure where to put it.
Waiting for your suggestions.
Without this change you cannot disable prefetching specific links.
It fixes an issue I've opened [here](https://github.com/nozzle/react-static/issues/970).

Add prefetch disabling for specific Links

---

packages/react-static-plugin-react-router/src/browser.api.js

Added hardcoded value to `StaticRouter` `context` property as suggested by @tannerlinsley [here](https://github.com/nozzle/react-static/issues/961#issuecomment-453672685)
Fixes #961

Fix nozzle/react-static#961

---

packages/react-static/src/index.d.ts

This PR just adds TypeScript definitions for the `static.config.js` file.
For users who are writing their `static.config` file in TypeScript, these definitions add type checking, code completion, etc.
For users who are writing their `static.config` file in plain JavaScript, but using a TypeScript-aware code editor (such as VSCode), these definitions add code-completion.  If they're using [`// @ts-check`](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html), then they'll also get type checking.

Added TypeScript definitions for `static.config.js` files

---

packages/react-static/package.json
packages/react-static/src/static/__mocks__/static.config.mock.jsx
packages/react-static/src/static/__tests__/getConfig.test.js
packages/react-static/src/static/getConfig.js

This PR enhances the `getConfig.js` file to support non-js file extensions for all of the React Static config files:
- `static.config.js`
- `node.api.js`
- `browser.api.js`
- `src/index.js`
All of these files are now loaded via a function called `resolveModule()`, which first attempts to load the module via Node's built-in `require.resolve()`.  This will automatically support any module extension that's built into Node (i.e. `.js`, `.mjs`, `.node`, etc).  It will also support any extensions that have been registered via Node require hooks, such as `.jsx`, `.ts`, etc.
If `require.resolve()` is unable to find the module, then the `resolveModule()` function falls-back to `fs-extra` via `fs.pathExistsSync()`.  Even this fallback approach is enhanced though.  It now supports any of the …

Support non-js extensions (.jsx, .mjs, .ts, etc.)

---

README.md
docs/plugins/README.md
packages/react-static-plugin-react-router/README.md

The react-router plugin was not linked in the plugin section, and if you find it, the dynamic route link in that particular readme is broken.
Also took the opportunity to add a site to your list.
Thanks for your work on a fantastic project.

Fix broken and missing links in docs and add site to readme

---

packages/react-static/src/browser/components/RouteData.js
packages/react-static/src/browser/index.js

Allow routeData to be used by the 404 page
- Edited `getRouteInfo()` to look for info on the `404` route if an error occurred trying to find info (unless it was trying to find info on the `404` route and failed)
- Edited `RouteData` component to check for info on the `404` route if a `routeError` was found for the current route, and if so, to use the 404 route info.
In version 5, it was possible to pass `routeData` to the 404 route. However, in version 6 this is no longer possible. Although the 404 route may access `siteData`, this is not sufficient for all use cases. It is very convenient to be able to pass `siteData` to the 404 route in unexpected situations, including: having a localized header/footer and wanting the header/footer to appear in the 404 route, without complicated the …

Enable routeData for the 404 page

---

packages/react-static/src/browser/components/RouteData.js
packages/react-static/src/browser/index.js

* Make sure shared data is always merged with data at the same point to create more predictable behaviour
* Load shared data when necessary
* Remove confusing return value of prefetch methods (since it's mutating the route info, the return value is never needed)
Fix nozzle/react-static#981
I've added some helper functions to determine whether or not the route info and/or its shared data should be loaded client-side. Although I feel like these might not be in the right place, but I'm not sure what would be a more appropriate place. Any suggestions?

Fix loading of shared data

---

packages/react-static/src/browser/components/Root.js
packages/react-static/src/browser/index.js

* Make sure a 404 template is registered for the '404' path when prefetching (instead of the original path)
* Make sure the path for a non-existing route is registered as error when hydrating the initial state
* Handle undefined return value of the getRouteInfo method
Fixes #1008

Fix registration of 404 route info

---

packages/react-static/src/static/exportRoute.js

The `outputPath` is required for `flushChunks` if `inlineCss: true` in `static.config.js`.
Fixes #971

outputPath required for inlineCss

---

packages/react-static/src/commands/bundle.js
packages/react-static/src/static/buildInfo.js
packages/react-static/src/static/clientStats.js
packages/react-static/src/static/extractTemplates.js
packages/react-static/src/static/getConfig.js
packages/react-static/src/static/prepareRoutes.js
packages/react-static/templates/basic/.gitignore
packages/react-static/templates/blank/.gitignore
packages/react-static/templates/stress-test/.gitignore

Move build artifacts from `dist/` to a new, `artifacts/` directory.
Build artifacts with potentially private data were being grouped together with build files.
This change makes it so they are sent to `artifacts/` instead.
Closes #1009

Move build artifacts to artifacts dir (#1009)

---

packages/react-static/babel-preset.js

Given that we only continuously compile during during dev, and given that the config only depends on `external` which isn't likely to change during development, a hard cache seems like the right solution.
Fixes #1023

Hard-cache babel config using `api.cache(true)`

---

packages/react-static/src/browser/utils/__tests__/shared.test.js
packages/react-static/src/browser/utils/index.js

* Don't rely on 'invalid' relative links, but check for hostname, protocol and port instead, fixing detection of absolute URLs without explicit protocol
* Removed redundant check for script links
* Added unit tests
`//www.example.com` would be considered 'prefetchable' because it would throw an error, and all invalid URLs were considered 'prefetchable'. By adding the base URL this will be fixed, it will create a valid URL object, but the hostname will differ and therefor the link will not be considered 'prefetchable'.

Improve prefetchable route detection

---

packages/react-static/src/browser/components/RouteData.js
packages/react-static/src/browser/index.js
packages/react-static/src/browser/utils/__tests__/shared.test.js
packages/react-static/src/browser/utils/index.js

Previously, in #1010 I had removed the return value of the `prefetch` method, since it was not used internally and seemed only confusing. Now I just realised this was actually a documented feature 😨 ... I restored the return value, making sure only for routes resolving in a 404  it will return `undefined`.

Restore route data return value for prefetch

---

packages/react-static/package.json
yarn.lock

React-static doesn't work out of the box without react-hot-loader, so it should be listed as a peerDependency.
I added the version that's included in the template projects to the peerDependency field of react-static.
This will make it easier to add react-static to a project without using a template, increasing flexibility.

Add react-hot-loader as peer dependency

---

docs/plugins/node-api.md

Fixes node-api documentation with a correct link to webpack rules directory.

node-api.md: fix link to webpack rules directory

---

packages/react-static/src/static/exporter.js
packages/react-static/src/static/exporter.threaded.js
packages/react-static/src/static/webpack/rules/cssLoader.js
packages/react-static/src/static/webpack/rules/fileLoader.js
packages/react-static/src/static/webpack/webpack.config.prod.js

Moves the output of the "node" app build to the artifacts folder. I also added a change that ignores file size limits to the URL loader, but was considering ignoring these files entirely (curious about your thoughts on this).
Since this compiled app is only used by route exporters, moving it out of the build folder should make its purpose more explicit while saving space.

Move node app build to artifacts folder

---

docs/plugins/README.md
packages/react-static/src/static/getConfig.js

See following paragraphs
- We will have an error with the following message if plugin wasn't resolved:
```Oh crap! Could not find a plugin directory for the plugin: "undefined". We must bail!```.
- > Plugins found in the /plugins directory of your project root. Eg. myPlugin would resolve to /plugins/myPlugins.js.
`myPlugin` won't resolve to `myPlugin.js` because `originalLocation` isn't modified in [resolvePlugin](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/getConfig.js#L152).

Update plugin resolution error message & docs

---

packages/react-static/src/browser/components/RouteData.js

Ref https://github.com/nozzle/react-static/commit/e1bdabfb0424557bc06fb14123c8845420cb35ca#r32536231
Add a check for creating `global.reloadAll` only in development.
We shouldn't pollute the global scope in production with a useless function.

Add global.reloadAll only in development

---

packages/react-static/src/static/exporter.js

The babel ignore path was not updated to the new `artifacts` folder, so the generated `static-app.js` was also parsed by Babel resulting in an extremely slow build.

Fix babel ignore path for build artifacts

---

docs/node-api.md

The Node API no longer supports passing a configuration object in v6. This updates the docs to reflect that change.

Update docs for Node API config argument

---

docs/node-api.md
packages/react-static/src/static/webpack/index.js

Makes `reloadRoutes` return a promise that resolves when routes are reloaded.
`reloadRoutes` now returns the promise returned by the inner `resolvedReloadRoutes`, instead of returning `undefined`.
Because route reloading is an async process, it's important to know when it's complete to accomplish a further action. For example, when using a preview app I might want to wait to redirect to the app until it's ready (when the routes have reloaded).
_Note:_ there's a possibility that this is a breaking change, if someone has some code that relies on the function returning `undefined`. But I think this is highly unlikely.
_Note_: I'm not quite sure what the `paths` argument is for- I took a stab at it in the docs, but let me know if I misunderstood it.

 Return promise from reloadRoutes

---

packages/react-static/src/browser/components/RouteData.js

When fetching shared data for 404 pages we should use the path to the 404 instead of the original path
Currently react-static will fail to load the shared data for 404 pages when navigating from another page, and it will simply remain in a loading state.

Fix shared route data for 404 pages

---

packages/react-static/src/browser/utils/index.js

Includes `port` in the base URL definition when template matching. 
Fixes a bug where routes weren't being matched correctly when using `localhost` (all routes returning 404). This was occurring because the port was being dropped from the base url definition.

Include port in base url when matching templates

---

packages/react-static/src/static/webpack/webpack.config.prod.js

Currently source code is deployed to the server even after `yarn build`
changed some flags in webpack.config.prod.js

prevent source code provisioning in release build

---

package.json
yarn.lock

Upgrade serve version in v5 branch to resolve https://nvd.nist.gov/vuln/detail/CVE-2018-3809
Upgraded v5 branch to use same version as v6, validated that behavior was the same without altering flags.
Resolves https://nvd.nist.gov/vuln/detail/CVE-2018-3809 for users of the v5 branch. In the case of react-static it seems unlikely it would be used in a case where it created a real vulnerability, but keeping alerts clear and relevant is useful. 
Lemme know if you want the yarn.lock excluded(?) or anything else, thanks!

Upgrade serve version for v5 

---

packages/react-static/node/index.js
packages/react-static/src/browser/utils/index.js
packages/react-static/src/node/getWebpackConfig.js
packages/react-static/src/node/getWebpackConfigSync.js
packages/react-static/src/static/__tests__/getConfig.test.js
packages/react-static/src/static/__tests__/webpack.test.js
packages/react-static/src/static/getConfig.js
packages/react-static/src/static/webpack/index.js

Add `getWebpackConfig` and `getWebpackConfigSync` methods to node API. Based off of discussions in #1036.
In short, provide better support for `eslint`. Read #1036 for full context.

Add `getWebpackConfig` and `getWebpackConfigSync` methods to node API

---

docs/api.md

Added note about Suspense dependency for useSiteData() hook. 
Added link to Suspense section in React's documentation.
Newcomers can be confused with the error about missing Suspense barrier. It should be explicitly stated in the manual.

Add note about requirement of using Suspense with useSiteData()

---

packages/react-static/src/browser/hooks/useSiteData.js
packages/react-static/src/static/webpack/runDevServer.js

In the original version importing `reloadClientData` inside **static.config.js** end up with an empty function declared [here](https://github.com/nozzle/react-static/blob/daf2d6bd17c3365d22beee086d0fb79e7431ec91/packages/react-static/src/static/webpack/runDevServer.js#L15) which is substituted [here](https://github.com/nozzle/react-static/blob/daf2d6bd17c3365d22beee086d0fb79e7431ec91/packages/react-static/src/static/webpack/runDevServer.js#L217) after socket creation, but substituted version can't be propagated to imports made before the substitution. 
Fixed version exports a wrapper function which will call up-to-date version of `reloadClientData()`.
The second part of the fix is dedicated to invalidating `siteData` inside `onReloadClientData()` handler of `useSiteData()` hook. This …

Fix for broken reloadClientData()

---

packages/react-static/src/static/getRoutes.js

- start cmd calls getRoutes with callback
- cb gets fed promise by afterPrepareRoutes instead of state object
Solution: await afterPrepareRoutes before calling the cb
Bugfix

Fix afterPrepareRoutes hook

---

packages/react-static/package.json
packages/react-static/src/static/webpack/rules/cssLoader.js
packages/react-static/src/static/webpack/webpack.config.dev.js
yarn.lock

HMR of CSS was not working for a fresh install of react-static 7.0.0 or 7.0.5, I tried upgrading extract-css-chunks-webpack-plugin to the 4.3.0 version (and it's corresponding webpack and css loaders modifications)
This change is required because when you install a brand new app from `ǹpx react-static create` (using 7.0.5)  CSS files do not HMR (I think it's related with a bug with extract-css-chunks-webpack-plugin@4.0.2) and in my opinion this is among the best or almost esential features for any react project.

Feature: upgrade extract-css-chunks-webpack-plugin to 4.3.0

---

packages/react-static/src/static/webpack/index.js

When `reloadRoutes` was called from the Node API, the rebuilt site had no template info returned from `/__react-static__/routeInfo/` calls. This was because routes were being rebuilt from the original config and previously loaded template data was lost. This change re-adds the template data on each call to `reloadRoutes`.

Fix Template Not Found error when reloading routes

---

packages/react-static/src/index.d.ts

I am developing a typescript react-static project and ran into the following issue while upgrading to v7 and using `useSiteData()` hook, which is blocking the build from compiling.
```
TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{}' has no compatible call signatures.
``` 
I've changed `useSiteData` to the same signature as `useRouteData` which resolves the issue above. Additionally simplified the `react-helmet` types to a passive export.
Fixes the error above that is currently blocking the app from compiling with `react-static` v7.0.6

chore: fix types

---

packages/react-static-plugin-reach-router/package.json

Updated peerDependency version for Reach Router to be at least 1.0.0, rather than an invalid version number. 
Yarn outputs `react-static-plugin-reach-router@7.0.0" has incorrect peer dependency "@reach/router@^0".`

react-static-plugin-reach-router: fix invalid peer dependency version

---

CHANGELOG.md
packages/react-static/bin/react-static

Passing a `--config` argument to the CLI does not work in v7 due to a key mismatch between CLI bootstrapping and getConfig function.
Changed the key for config file path from `config` to `configPath` to match the use case in `getConfig.js`
This fixes #1111
This is my first contribution to react-static. Let me know how can I do better! :)

Fix using custom config with CLI

---

docs/plugins/README.md

There were several newer plugins missing from the list in the docs, so I thought it'd be helpful to update it.
I did notice while updating the list that `react-static-plugin-favicons` is listed under 'official plugins', but actually seems to be maintained outside of the main React Static repo - this seemed a bit misleading, so I seperated it out. That said, this does raise the question of 'should this repo maintain a list of unofficial plugins?' - happy to make changes if you think the answer is no or if you want me to merge the lists back together!
* Added all official plugins to the list in the docs.
* Moved `react-static-plugin-favicons` to a seperate list of unofficial plugins.
The main motivation for this was discoverability - I spent a little time trying to set up MDX for myself, …

Update list of official plugins in the docs

---

packages/react-static/src/static/components/Redirect.js

Fixes a bug where redirects had `undefined` prepended to them when `REACT_STATIC_PUBLIC_PATH` env var was not set.
Added empty string fallback for env var in Redirect component.

[v6] Handle undefined REACT_STATIC_PUBLIC_PATH in redirects

---

docs/guides/aws-lambda.md

Since the `static.config.js` file can be JSX, it was blowing up since the extra `binHelper` which is executed when in local, wasn't being executed in Lambda.

Lambda Documentation wasn't working as it was

---

docs/api.md
docs/config.md

Documentation mentioned `reloadRoutes` which appears to no longer be available in v7. https://github.com/nozzle/react-static/issues/985#issuecomment-478672421 recommends to use `reloadClientData`. 
- renamed `reloadRoutes` to `reloadClientData` in API.md
- renamed link in `config.md` from `node-api.md` to `api.md` and from `reloadRoutes` to `reloadClientData`

Update documentation "reloadRoutes" -> "reloadClientData"

---

CHANGELOG.md
packages/react-static-plugin-mdx/package.json
yarn.lock

Just bumping @mdx-js/loader dependency to v1 in react-static-plugin-mdx. This upgrade should require no additional changes.
MDX can have many unforseen edge cases, and it's a good idea to keep its dependencies up-to-date because the changes are usually bugfixes.
...but only for the plugin!

Bump @mdx-js/loader in MDX plugin

---

CHANGELOG.md
packages/react-static/package.json
packages/react-static/src/static/webpack/webpack.config.dev.js
yarn.lock

According to the [webpack-dev-server documentation](https://webpack.js.org/guides/hot-module-replacement/ ), the client should not be an entry. It seems to be an old way of configuring (I found this [article from 2016](https://medium.com/@rajaraodv/webpacks-hmr-react-hot-loader-the-missing-manual-232336dc0d96) that shows the client as an entry point).
When this line is present, the webpack-dev-server is actually required _twice_, as you can see in the following image:
1. once from the entry (`'webpack-dev-server/client?...'`)
2. once from the plugin (`'../../webpack-dev-server/client?...'`)
This would normally not be an issue. Identical requires are only executed once. However, `webpack-dev-server` as a plugin expects you to write:
```javascript
devServer: {
host: …
```

Remove webpack-dev-server/client from entry

---

docs/plugins/node-api.md
packages/react-static/src/static/plugins.js
packages/react-static/src/static/webpack/buildProductionBundles.js

Adds an `afterBundle` hook to the Plugin Node API 
As discussed in #1158, I'm planning to copy the functionality of https://github.com/axe312ger/gatsby-plugin-netlify-cache into a React Static plugin, but also want to support a setup that may run `react-static bundle` and `react-static export` individually and perform some caching at the end of the bundle task

Adds `afterBundle` hook to Plugin API

---

docs/api.md
docs/config.md

Revert https://github.com/nozzle/react-static/pull/1145, in which I not-fixed a reference to no-longer existing `reloadRoutes` by replacing it with `reloadClientData`, which exists but does something else. Point to correct function `rebuildRoutes`. Addresses #1144.

Fix docs reference to wrong function

---

packages/react-static/src/index.d.ts

Updated `index.d.ts` so that you can compile the react-static typescript template when using specific parts of the API.
* Fixed invalid typescript definitions for Routes ( it's actually not for Routes but is rather hijacked by @reach/router, but that's just how it works it seems...).
* Added missing typescript definitions for `withRouteData` & `withSiteData`
Fix broken typescript definitions

Fix TypeScript definitions for Routes & add withRouteData & withSiteData

---

packages/react-static/bin/react-static

We had a bug in a react-static 7 app that was being deployed via CI. It went "blank" in our production environment because the CI pipeline didn't detect the failing build: The `react-static`-command exit status is still `0` whenever an error occurs while building...
This change should fix that.

Please use non-0 exit status whenever CLI command fails

---

packages/react-static/templates/typescript/package.json
packages/react-static/templates/typescript/static.config.js

`react-static create` somehow doesnt install latest patch versions of RS and this is bad for initial experience
an attempt to fix https://github.com/nozzle/react-static/issues/1163 for good - what do we think?

use latest versions for typescript template

---

packages/react-static-plugin-sass/package.json
packages/react-static-plugin-sass/src/node.api.js

Add postCSS config and an autoprefixer to SASS plugin, just like the LESS config.
- autoprefixer
- css-loader
- postcss-flexbugs-fixes
- semver
Keep a cohesion between the different plugins

add postcss autoprefixer config to sass plugin

---

CHANGELOG.md
packages/react-static-plugin-mdx/README.md
packages/react-static-plugin-mdx/src/node.api.js

MDX has options like `remarkPlugins` and `rehypePlugins`, now it's possible to configure them through react-static-plugin-mdx as `mdxOptions`.
Let me know if you would like a different API!
It makes it possible to configure MDX by adding [plugins](https://mdxjs.com/advanced/plugins).

Allow passing options to MDX webpack loader

---

packages/react-static-plugin-less/package.json

`src` has a `node.api.js` file, not a `index.js` file, so `main` should be `node.api.js`.
The 7.0.10 npm install doesn't seem to have a compiled `node.api.js`, as there is only a copy in `src` and none in the root. This is probably the cause of this issue: https://github.com/nozzle/react-static/issues/1150
Fix npm package.
https://github.com/nozzle/react-static/issues/1150

less plugin pointing to incorrect main file

---

packages/react-static/src/static/webpack/webpack.config.dev.js
packages/react-static/src/static/webpack/webpack.config.prod.js

react-static is plagued by a problem that nextjs also suffered from. See https://github.com/jaredpalmer/after.js/issues/49 for example. Here is the commit that resolved the problem: https://github.com/zeit/next.js/pull/3731/files

Allow react/react-dom submodules to work

---

packages/react-static-plugin-css-modules/package.json
packages/react-static-plugin-css-modules/src/node.api.js
packages/react-static-plugin-less/package.json
packages/react-static-plugin-less/src/node.api.js
packages/react-static-plugin-sass/package.json
packages/react-static-plugin-sass/src/node.api.js
packages/react-static/package.json
packages/react-static/templates/blank/yarn.lock
packages/react-static/templates/stress-test/yarn.lock
packages/react-static/templates/typescript/yarn.lock
yarn.lock

Its been a long and hard road. But HMR should now work reliably for any and all types of style content. Allowing users to reload real CSS files. No more style-loader needed
Re-adding extract-css-chunks HMR system back to react static development mode after joining forces with mini-css authors
I get a staggering amount of emails from GitHub issues on react static. Id like less on the CSS subject
fixes #1169

fix: HMR of real CSS files in development

---

packages/react-static/src/browser/index.js

The prefetch attribute is not an attribute on anchor elements. The preferred way to do custom attributes is using data-* attributes or custom web elements.
When using anchor attributes the only potential candidate would be rel="prefetch", but that is not enabled for anchor elements (only link elements):
https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
This allows TypeScript or JavaScript over TypeScript (@ts-check // tsconfig.json allowJs: true) to correctly accept a data-prefetch override attribute. 
Additionally it limits the prefetching to:
- no attribute
- attribute value = `'true'`
- attribute value = `'visible'`
This allows for other components to add checks for other values such as `mount` (when it's found), `hover` (when it's hovered) or something different. …

Fix prefetch attribute

---

packages/react-static/src/static/__tests__/getConfig.test.js
packages/react-static/src/static/getConfig.js

This change stops the removing of trailing slashes in user-provided assetsPath (by ways of the `static.config.js`).
Without this, when defining a custom assetPath, navigating is broken in development as well as in the production build of the affected site/project. This is due to the code-split template files of each page that cannot be loaded. Atleast that's what happened in our project after trying out the assetsPath setting.
Example:
User supplies `https://example.com/` as assetsPath.
In the built sites, assets now are loaded similar to this when navigating (note the missing slash after .com): `https://example.comsrc/container/example.js`
Note: Initial load of each page works, however when navigating, the main.js script fails to load the template js files of the page we want to navigate …

Don't strip trailing slashes of user-provided assetsPath / Append trailing slash to assetsPath, if necessary

---

docs/plugins/README.md

I added the plugin I wrote for injecting the GTM script tag to the plugins list.

Add unofficial react-static-plugin-google-tag-manager to plugins list

---

packages/react-static/src/static/buildXML.js

Follow up to #1137, for the sitemap builder.
Makes undefined `REACT_STATIC_PUBLIC_PATH` fall back to an empty string.

[v6] Handling undefined public path in sitemap

---

docs/plugins/README.md
packages/react-static-plugin-stylus/.babelrc
packages/react-static-plugin-stylus/.gitignore
packages/react-static-plugin-stylus/README.md
packages/react-static-plugin-stylus/package.json
packages/react-static-plugin-stylus/src/node.api.js

Adds a plugin for loading stylus `.styl` files.
Because I prefer Stylus and there wasn't one yet.

Add react-static-plugin-stylus

---

packages/react-static/package.json
packages/react-static/src/static/components/BodyWithMeta.js

see https://twitter.com/HenrikJoreteg/status/1143953338284703744
routeInfo is passed as json string and evaluated as JSON at runtime (which should increase the startup performance)
performance is always an issue ;)

tweak startup perf by JSON.parse routeInfo

---

packages/react-static-plugin-sass/src/node.api.js

When using the Sass plugin, a Flash Of Unstyled Content may appear in a built application.
This seems be caused by the missing configuration of Webpack's [Split Chunk Optimization](https://webpack.js.org/plugins/split-chunks-plugin) when using this plugin. 
The default CSS loader loads all CSS in a single chunk by default (when the `extractCssChunks` configuration option isn't set) [See this related source code](https://github.com/nozzle/react-static/blob/master/packages/react-static/src/static/webpack/webpack.config.prod.js#L55), but the SASS module is missing this configuration / is not not patching up the related configuration.
This PR should fix that and fixes issue #1177.

Prevent FOUC in sass plugin

---

packages/react-static/src/static/webpack/rules/cssLoader.js

Running `react-static` currently prints this warning:
```
Replace Autoprefixer browsers option to Browserslist config.
Use browserslist key in package.json or .browserslistrc file.
Using browsers option cause some error. Browserslist config
can be used for Babel, Autoprefixer, postcss-normalize and other tools.
If you really need to use option, rename it to overrideBrowserslist.
Learn more at:
https://github.com/browserslist/browserslist#readme
https://twitter.com/browserslist
```
It goes away by renaming `browsers` to `overrideBrowserslist` as
suggested.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

cssloader: Rename "browsers" to "overrideBrowserslist"

---

docs/plugins/README.md

I'm adding a link to the Yandex Metrica plugin in the plugins docs.

 Mention react-static-plugin-yandex-metrica in the plugins docs

---

packages/react-static-plugin-reach-router/src/browser.api.js

Fixes https://github.com/nozzle/react-static/issues/1182 - where static export doesn't work when you set a `basePath` on your config.
Reach router (plugin) specifically makes the location URL absolute - meaning that given a `staticInfo.path` of `blog/post/79`, it'll transform it to `/blog/post/79` - which is outside of our app, hence rendering nothing. The `ServerLocation` lives outside of the main router, hence it needs to provide the full URL, with the base path.
I haven't added any test, as I didn't see any in the Reach Router plugin. For the CHANGELOG summary, should I just add a section to it (there's no "unreleased" section) ?

[Reach Router] Add base path to server location URL

---

packages/react-static/src/static/plugins.js

Yo dawg, I heard you like plugins, so I added 'plugins' to plugins.js so you can use plugins while you write plugins.
Fixes https://github.com/react-static/react-static/issues/1143

Allow plugins to use plugins

---

package.json
packages/react-static-plugin-sass/package.json
yarn.lock

Update `node-sass` to `^4.12.0` and instruct yarn to install `fsevents@^1.2.9`, which allows a fresh install on Node 12.
Per https://github.com/sass/node-sass/issues/2632#issuecomment-487247910 `node-sass@^4.12.0` supports Node 12. `node-sass` is a direct dependency of `react-static-plugin-sass`.
Per https://github.com/fsevents/fsevents/issues/272#issuecomment-487645485 `fsevents@^1.2.9` supports Node 12. `fsevents` is a transitive dependency of a couple of direct and indirect dependencies.
```
❯ yarn why fsevents
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "fsevents"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "fsevents@1.27"
info Reasons this module exists
- "_project_#chokidar" depends on it
- Hoisted …
```

Node 12 (stable) support

---

packages/react-static/src/static/webpack/rules/fileLoader.js

The webpack file-loader rule for node didn't have a limit, this caused the actual generated files to never include the url for the image file and instead inline everything as a base64.
Should fix: 
#1221 and somewhat resolve the issue in #1157

Limit added to node fileloader rule to prevent all images from being inlined as base64 strings,

---

packages/react-static/src/static/extractTemplates.js

Consider that we store the artifacts on an OS temporary directory (such
as what you would get with `mktemp -d` or `node-tmp`) which we can
assume for simplicity purposes to be `/tmp/react-static`.
In the snippet above, `route.template` is a path such as
`/home/johndoe/site/lib/pages/main.js`. Therefore `path.relative()` will
calculate the path to `/home/johndoe/site/lib/pages/main.js` from
`/tmp/react-static`, so the result will be something like
`../home/johndoe/site/lib/pages/main.js` which makes no sense and will
cause react-static to fail.
What we really intended is `path.resolve()`, so that the user still gets
`/home/johndoe/site/lib/pages/main.js`.
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

Fix route template path handling

---

packages/react-static/src/static/components/BodyWithMeta.js
packages/react-static/src/static/components/__tests__/__snapshots__/BodyWithMeta.test.js.snap
packages/react-static/src/static/extractTemplates.js
packages/react-static/src/static/getConfig.js
packages/react-static/src/static/getRoutes.js

The current approach assumes that the current directory when running
`react-static` is the root path, which might not be the case if you
customize the root.
This came up as I'm developing a CLI module that embeds `react-static`,
takes some command line arguments, spawns `react-static` using files
inside the CLI module, and stores the results in the user's destination
directory.
When the tool (and therefore `react-static`) are installed globally, my
`ROOT` is:
```
/Users/jviotti/.nvm/versions/node/v9.11.2/lib/node_modules/<my-cli>
```
And `__dirname` from `src/static/getRoutes.js` becomes:
```
/Users/jviotti/.nvm/versions/node/v9.11.2/lib/node_modules/<my-cli>/node_modules/react-static/lib/static
```
Given those two variables, the code in `getRoutes.js` will evaluate the
`Default404` …

Don't use a relative path to resolve Default404 template

---

packages/react-static/src/static/generateBrowserPlugins.js
packages/react-static/src/static/webpack/webpack.config.dev.js
packages/react-static/src/static/webpack/webpack.config.prod.js

I've been lately hitting various issues due to the way react-static
defaults to relative paths, which tend to break as soon as you tweak
react-static directories (artifacts, dist, root, etc) to locations that
are not the ones react-static recommend.
Most of these issues are automatically resolved by switching to
`path.resolve()`, which always results in absolute paths, and avoids
large `../../` chains if the second argument is absolute.
See: https://github.com/nozzle/react-static/pull/1250
See: https://github.com/nozzle/react-static/pull/1253
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

Don't use path.relative() in react-static/src/static

---

packages/react-static/src/browser/utils/__tests__/shared.test.js
packages/react-static/src/browser/utils/index.js
packages/react-static/src/static/__mocks__/defaultConfigProduction.mock.js
packages/react-static/src/static/__tests__/getConfig.test.js
packages/react-static/src/static/getConfig.js
packages/react-static/src/static/webpack/webpack.config.prod.js

Fixes #1141.
Implements the changes discussed [here](https://github.com/react-static/react-static/pull/1196#discussion_r290831191) to ensure that `publicPath`/`process.env.REACT_STATIC_PUBLIC_PATH` is always absolute.
This also address the issue with the `getRoutePath` utility, ensuring it strips `basePath` when it's present.

Ensure publicPath is always absolute

---

docs/config.md
packages/react-static/src/static/__tests__/extractTemplates.test.js
packages/react-static/src/static/extractTemplates.js

Implement fix discussed here: https://github.com/react-static/react-static/pull/1253#issuecomment-519566900.
> Per the current documentation, `route.template` should be relative to `static.config.js`/the root of the project - so with the change proposed, we'd keep this behavior, as well as support supplying an absolute path. The resulting `route.template` would however always be absolute, ensuring build artifacts can be stored outside of the repo.
I've added some tests around `extractTemplates`, I think some integration tests would probably be more useful here but didn't get to figure it out.

Handle relative route template

---

docs/plugins/README.md

Fixed broken link in [docs/plugins/README.md](https://github.com/react-static/react-static/blob/5a38e1c818ef57c94b01083ac120d592036f8afd/docs/plugins/README.md)
- react-static-plugin-typescript
- react-static-plugin-sitemap
- To improve document quality.

Fix broken link in docs/plugins/README.md

---

README.md

Hello, thank you for your great work!
I'd like to add [Weekly Best of JavaScript](https://weekly.bestofjs.org/) to the list of sites made with _React Static_.
_Weekly Best of JavaScript_ is the the weekly newsletter from [Best of JavaScript](https://bestofjs.org/) application.
It's made with React Static 7, as you can see on [GitHub repo](https://github.com/bestofjs/bestofjs-weekly).
As a side note, _React Static_ is doing well on _Best of JavaScript_: https://bestofjs.org/projects/react-static

Add "Weekly Best of JavaScript" site to README.md

---

packages/react-static/src/static/webpack/runDevServer.js

Added `http://` in front of dev-server url which makes it clickable in terminal.
#1302

Make dev-server url clickable

---

packages/react-static/bin/react-static

Prevented undefined property warning from showing up.
`init()` doesn't return a `Promise` and therefore using `catch()` throws the respective undefined error. 
closes #1260

fix: prevent undefined property warning

---

packages/react-static/src/commands/start.js

Fixes the issue described in #1148. When using a custom `Document` in the react-static config and running `react-static start`, the `Document` props did not contain `state.siteData`.

Fetch state.siteData in dev (closes #1148)

---

docs/plugins/README.md

Fix broken links for "What can plugins do" and example plugin.
Make docs great again. Fix 404 link.

Fix broken links on plugin docs

---

docs/api.md
docs/guides/animated-routes.md

Rewrote some of the docs regarding the `Routes` component, particularly to correct language and examples suggesting that you can use the children-as-function pattern with it.
In trying to implement this component's advanced features in my own site, I found that the docs were misleading and in some cases just wrong. The names are still somewhat confusing (why is it called `getComponentForPath` if it returns an element, not a component?) but at least the information is now correct (as far as I can tell from looking through the source).
I also updated the `animated-routes` example the best I could, but I'm not really familiar with `react-spring` and there are still some pretty big issues in the example. Namely, the temporary routes kind of stack on top of each other while transitioning, …

Updated docs about `Routes` component

---

packages/react-static/src/static/components/HeadWithMeta.js
packages/react-static/src/static/components/__tests__/__snapshots__/HeadWithMeta.test.js.snap

This ensure that if you set a `<meta charSet="utf-8" />` (actually, any meta tag) in your [Document](https://github.com/react-static/react-static/blob/master/docs/config.md#document), it will be rendered higher up, hence be valid and observed by browsers (charset must be in the first 1024 bytes).
https://spectrum.chat/react-static/general/hello-are-there-any-known-bugs-around-unicode-in-react-static~0ae1abd4-c64e-4f2c-8e74-63bf70479528
Fix the issue described here: https://spectrum.chat/react-static/general/hello-are-there-any-known-bugs-around-unicode-in-react-static~0ae1abd4-c64e-4f2c-8e74-63bf70479528

Render Document meta element higher up

---

CHANGELOG.md
docs/plugins/README.md

This adds the [`react-static-plugin-file-watch-reload`](https://github.com/wappsify/react-static-file-watch-reload) plugin to the plugin list.
I just published that plugin, it wraps `chokidar` for easy file watching in development mode.

Add unofficial plugin react-static-plugin-file-watch-reload to plugins list

---

packages/react-static/src/bootstrapPlugins.js
packages/react-static/src/bootstrapTemplates.js
packages/react-static/src/static/__tests__/extractTemplates.test.js
packages/react-static/src/static/extractTemplates.js
packages/react-static/src/static/generateBrowserPlugins.js
packages/react-static/src/static/generateTemplates.js
packages/react-static/src/static/getConfig.js
packages/react-static/src/static/webpack/webpack.config.dev.js
packages/react-static/src/static/webpack/webpack.config.prod.js

Attempts to fix https://github.com/react-static/react-static/issues/1303.
Absolute paths are found in the exported bundles. This is surprising, can leak information about your build system, and will cause [webpack longterm caching](https://webpack.js.org/guides/caching/) to not work if you build your site in different directories over time (or on multiple servers).
(copy of https://github.com/react-static/react-static/issues/1303#issuecomment-535139590) I've tested changing both `paths.dist` and `paths.temp` to point outside of the working directory. This works fine and no absolute paths end up in the generated files, ensuring consistent hashing even when the build directory changes.
However, I can't get `yarn build` to successfully run when also changing `paths.buildArtifacts` to a …

Remove absolute paths from generated JS

---

docs/api.md

Removed the 404 link and added the available working reference link for Animated Routes in api docs.
https://github.com/react-static/react-static/blob/master/docs/guides/animated-routes.md
Just a documentation quick fix.

Fix link to animated routes

---

CHANGELOG.md
packages/react-static-plugin-sitemap/src/buildXML.js

Fixes #1233 and #1312
`process.env.REACT_STATIC_PUBLIC_PATH` is set in build process.
The value comes from `config.publicPath` so we can simply set it in `buildXML.js`
It will fix these issues:
#1233
#1312

Fixes #1312 - Makes sure prefixPath is set in sitemap plugin

---

CHANGELOG.md
packages/react-static-plugin-less/README.md
packages/react-static-plugin-less/src/node.api.js
packages/react-static-plugin-sass/README.md
packages/react-static-plugin-sass/src/node.api.js
packages/react-static-plugin-stylus/src/node.api.js

Pass options from sass plugin to css-loader to enable css modules.
Add `cssLoaderOptions` property to enable configuration of css-loader.
- [✓] Changed code
Enables developers the CSS modules feature by providing options to configure css-loader used inside the react-static-plugin-sass
- [ - ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ - ] Bug fix (non-breaking change which fixes an issue)
- [✓] New feature (non-breaking change which adds functionality)
- [ - ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [✓] I have updated the documentation accordingly
- [✓] I have updated the CHANGELOG with a summary of my changes
- [ - ] My changes have tests around them

Pass options to css-loader

---

CHANGELOG.md
packages/react-static/src/browser/utils/__tests__/shared.test.js
packages/react-static/src/browser/utils/index.js

The documentation states that the `basePath` configuration can be used to host a site at a specified path, e.g. `https://mysite.com/blog`. However, the regular expression we use doesn't catch `/blog`, only `/blog/*`.
* Made the path `/{basePath}` resolve to `/` when determining the route path.
Allows sites hosted at a particular path to function as expected and as described in existing documentation.

Handle basePath without trailing slash

---

CHANGELOG.md
packages/react-static-plugin-stylus/README.md
packages/react-static-plugin-stylus/package.json

Fixed react-static-plugin-stylus to work correctly.
The package `react-static-plugin-stylus` on npmjs.com is missing its main file.
```
$ ls -l node_modules/react-static-plugin-stylus/
total 24
-rw-r--r--   1 horie  staff  1077 Jan 12 22:48 LICENSE
-rw-r--r--   1 horie  staff   629 Jan 12 22:48 README.md
drwxr-xr-x  10 horie  staff   320 Jan 12 23:33 node_modules
-rw-r--r--   1 horie  staff   840 Jan 12 22:48 package.json
drwxr-xr-x   3 horie  staff    96 Jan 12 23:33 src
```
```
$ grep main node_modules/react-static-plugin-stylus/package.json 
"main": "index.js",
```
- Changed `main` file from `index.js` to `node.api.js` since `node.api.js` will be created when you run `$ yarn build`.
- Changed README to describe about `react-static-plugin-stylus`. I'm not sure why but it notes about …

Fix #1244 - Publish

---

CHANGELOG.md
packages/react-static/src/browser/index.js

Fixes issue where a route with a dot in it doesn't work.
Fixes https://github.com/react-static/react-static/issues/1354
- [x ] Bug fix (non-breaking change which fixes an issue)

Commented out code that will "deny all files with extension other than .html" to allow routes with dots in them.

---

CHANGELOG.md
packages/react-static/src/utils/progress.js

Progress module writes on stderr, instead of stdout.
I changed the output from stderr to stdout.
I use `rush` (https://rushjs.io/) to handle a monorepo.
It looks for stderr output to check if there are errors during the build step.
If there's an error, it stops the build pipeline.

Progress module writes on stderr, instead of stdout.

---

CHANGELOG.md
packages/react-static/src/browser/index.js
packages/react-static/src/static/webpack/buildProductionBundles.js

Wherea Webpack stats color output was hard wired to be true, this PR proposes to use `chalk.supportsColor` to automatically enabled/disabled color output.
This ensures that in environment where color output is not supported, no "color escape code" is rendered to screen.
Example of output currently produced on environment that don't support colored output:
```
Version: webpack ·[1m4.33.0·[39m·[22m
Time: ·[1m80841·[39m·[22mms
Built at: 01/24/2020 ·[1m8:46:42 PM·[39m·[22m
```

Use chalk.supportsColor over hard wiring color output

---

.gitattributes
CHANGELOG.md
CONTRIBUTING.md
docs/config.md
packages/react-static/src/index.d.ts
packages/react-static/src/static/__tests__/exportRoute.test.js
packages/react-static/src/static/components/BodyWithMeta.js
packages/react-static/src/static/components/__tests__/BodyWithMeta.test.js
packages/react-static/src/static/components/__tests__/__snapshots__/BodyWithMeta.test.js.snap
packages/react-static/src/static/exportRoute.js

This PR adds a new object to the `state` attribute of `DocumentProps` called `inlineScripts`. The keys of the `inlineScripts` object are descriptive names of the scripts and contain the script source and its SHA256 hash. There is currently only one inline script, the route info hydration script:
```json
{ 
"routeInfo": { 
"script": "window.__routeInfo = JSON.parse(\"route data as json string\")", 
"hash": "sha256-<base64-value>",
}
}
```
These hashes can be used to construct a Content Security Policy in a meta tag without needing `unsafe-inline` for scripts. 
Resolves #1362

Add inline script hashes to DocumentProps

---

.gitattributes

Closes https://github.com/react-static/react-static/issues/1339.
Before this change, upon cloning `react-static` to my computer I would get the following, per https://github.com/react-static/react-static/pull/1373#issuecomment-582525419.
```
~/Sites/react-static master*
❯ git status
On branch master
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   media/media.sketch
no changes added to commit (use "git add" and/or "git commit -a")
~/Sites/react-static master*
❯ git diff
warning: CRLF will be replaced by LF in media/media.sketch.
The file will have its original line endings in your working directory
diff --git a/media/media.sketch b/media/media.sketch
index …
```

Mark .sketch file as binary

---

docs/plugins/node-api.md

Fixed the function definition example for `beforeRenderToElement` in the `node.api.js` docs
There was error in the docs

Fixed the function definition example

---

CHANGELOG.md
packages/react-static/src/browser/index.js
packages/react-static/src/static/webpack/runDevServer.js

The default host and port is http://localhost:4000, but if we want change that we cant.
Just add 2 environments variables `REACT_STATIC_MESSAGE_SOCKET_PORT` and `REACT_STATIC_MESSAGE_SOCKET_HOST` and its fine.
It's required because today i cant change this host and port and i use react-static running on docker with a custom url and i want that xhr polling to resolve at the same base uri.
My example: 
- Run `react-static start` inside a docker container.
- Use a proxy to redirect my request `http://site.localhost:80` to my docker container network ip at port 3000 (`172.25.0.5:3000`)
- So i need the xhr polling request to resolve as `http://site.localhost:4000` because i have another proxy to redirect `http://site.localhost:4000` -> `172.25.0.3:4000`

Add environment variables to change xhr polling (DevServer) host and port.

---

CHANGELOG.md
docs/config.md
packages/react-static/src/static/webpack/runDevServer.js

This fixes the issue where https is configured but the "App serving at" URL in the console is still displayed with the http protocol.
When developing locally one might want to run the application in https to avoid missing mixed content issues for example, or to take advantage of browser features that require HTTPS. Right now it is already possible to configure the app for https operation by using `static.config.js`:
```js
export default {
devServer: {
https: true,
key: fs.readFileSync('/path/to/localhost.key'),
cert: fs.readFileSync('/path/to/localhost.crt'),
},
}
```
however, once this option is set, the console output remains unchanged due to the currently hard-coded `http://` prefix
> Added a section on how to enable HTTPS for local development so folks don't need to look up how to …

Add conditional protocol output to serving message

---

docs/api.md

`rebuildRoutes` cannot be called before `getRoutes()` leading to the gotcha in issue #1403. This PR applies the recommended fix  by @SleeplessByte to the documentation. 
- Added `areRoutesBuilt` flag that gets set to `true` the first time `getRoutes` is run
The documentation for `rebuildRoutes` do not account for the fact that `getRoutes()` must be called first. Relevant issue #1403.

#1403 Update api docs for rebuildRoutes

---

CHANGELOG.md
packages/react-static/src/static/webpack/runDevServer.js

Fix for https://github.com/react-static/react-static/issues/1093
The suggestion in the issue above was to update the latestState variable directly, but as mentioned this doesn't work. I believe this is primarily because the routes are set already and `before` is not called when the webpack dev server is invalidated. 
Testing locally this works, just wanted a second opinion before i look into adding tests as it may be overly heavy-handed.
comes from https://github.com/react-static/react-static/issues/1093. In summary, if you try to call `reloadClientData` in static.config.js the reload happens but the data isn't actually re-retrieved.

Add call to fetchSiteData when reloadClientData is called in runDevserver.js

---

docs/api.md

Fixed api.node.js typo in api.md - should be node.api.js.

Fix typo in api.md.

---

CHANGELOG.md
packages/react-static/src/browser/index.js
packages/react-static/src/static/webpack/runDevServer.js

Rework how the communication with SocketIO is done. Instead of talking directly with the SocketIO server, proxy the `/socket.io` path to the SocketIO domain.
Following the steps outlined in the documentation to [enable HTTPS for local development](https://github.com/react-static/react-static/blob/master/docs/config.md#devserver), Safari fails to request data from the SocketIO domain (http://localhost:4000), has it isn't served over HTTPS. Chrome has no issue with this.
Safari logs the following error in the console, originating from `polling-xhr.js`:
> Not allowed to request resource
> XMLHttpRequest cannot load http://localhost:4000/socket.io/?EIO=3&transport=polling&t=N7DEOQw due to access control checks.
I have tried to run the SocketIO server on an HTTPS server, without any luck.

Proxy '/socket.io' to socket server

---

CHANGELOG.md
packages/react-static/src/static/webpack/rules/fileLoader.js

In production build, images larger than 10,000 bytes generates wrong
path and it generates 404 error.
Related issue is here : #1328

Fix wrong image route in production build

---

CHANGELOG.md
packages/react-static/src/static/webpack/webpack.config.prod.js

Update the `webpack-node-externals` configuration so it bundles `react-universal-component`, in turn fixing the static export. On a fresh 7.3.0 project (using the basic template), running `yarn build` will not output anything that's within a template.
This ensure it get's bundled and that rendering on the server works. Without doing this it seems like templates do not render during the export.
This seem to have been introduced by me, in https://github.com/nddery/react-static/commit/e040cbf6fec58c49a3a20b2ffab70a7d62713457. My understanding is that where we previously used `process.env.REACT_STATIC_UNIVERSAL_PATH`, `nodeExternals` would not see the request as a node module, and would in turn bundle it. They do mention using alises in their …

Whitelist react-universal-component from externals

---

CHANGELOG.md
packages/react-static/bin/react-static

Ensure `init()` always return a `Promise`. This prevents the issue described in https://github.com/react-static/react-static/issues/1260.
Since `init()` returns a `Promise`, it would need to be awaited for. However, we can't `await` at the top-level, so we would have needed to wrap the `try/catch` in an `async` function for it to work, like so:
Example of awaiting:
```js
async function main() {
try {
await init()
} catch(e) {
console.trace(e)
process.exit(1)
}
}
main()
``` 
This just seem overly complex, so I went for the `catch` as it's nicer than wrapping the `try/catch`.
- `yarn build` with an error thrown, exit status is 1.
- `yarn build` with no error thrown, exit status is 0.
- `yarn react-static` logs the usage info, exit status is 0, no error logged
I have not added tests yet, …

Ensure a non-zero exit status code when build has errors 

---

CHANGELOG.md
docs/concepts.md
packages/react-static/src/browser/index.js

These changes bring support for older browsers with updated polyfills
Over releases browser support for IE 11 has stopped. This PR brings compatibility. 
Fixes issues #1361

Updated browser support docs for IE 11

---

CHANGELOG.md

Updated the changelog to reflect 7.4.1.
@SleeplessByte I have not run `yarn lerna version`, (nor `publish`), as that would try and push tag to my remote, as I understand it. This said, I also haven't updated `lerna.json` or `package.json` versions. Maybe I should run `yarn lerna version --no-push`, which would update all versions, create commits and tags, but not push them ? Seems like something that maybe should happen on master (I'm not familiar with any of this..) ?
Create a 7.4.1 release, which contains some bugs fixes:
- Ensure a non-zero exit status code when build has errors ([#1451](https://github.com/react-static/react-static/pull/1451))
- Updated browser support docs for IE11 support ([#1461](https://github.com/react-static/react-static/pull/1461))

7.4.1 release

---

CHANGELOG.md
packages/react-static/templates/typescript/package.json

This PR simply removes the no-longer-needed dependency on `@types/react-hot-loader`.
I wasn't sure if an update to the CHANGELOG was warranted. If it is, let me know and I'll be happy to add that.
*UPDATE:* Added summary to CHANGELOG.md
* `react-hot-loader` bundles its own types since [v4.0.0](https://github.com/gaearon/react-hot-loader/releases/tag/v4.0.0)
* When running `$ npx react-static create` with the TypeScript template (before this change), `npm` would give the following warning:
> npm WARN deprecated @types/react-hot-loader@4.1.1: This is a stub types definition. react-hot-loader provides its own type definitions, so you do not need this installed.

Remove @types/react-hot-loader from TypeScript template

---

.eslintignore
CHANGELOG.md
docs/api.md
packages/react-static-plugin-preact/README.md
packages/react-static-plugin-preact/package.json
packages/react-static-plugin-preact/src/node.api.js
packages/react-static/src/browser/index.js
yarn.lock

The preact plugin is currently not functioning due to the alias pointing to the wrong references. See #1331
- Upgrade preact to latest version
- Remove preact-compat (is now included in preact core)
- Change alias to correctly reference the actual react packages
- Add prefresh to replace react-hot-reload
see #1331 
Additional Notes: I'm not 100% sure how the dependency management works with yarn workspaces and also unsure how to test the actual code on this branch with an example project. Please let me know what I can do to pull in the plugin from this branch into a fresh react-static project.

Update preact plugin

---

CHANGELOG.md
packages/react-static-plugin-styled-components/README.md
packages/react-static-plugin-styled-components/package.json

Expands version range in peer dependency of styled-components plugin
Not adding styled-components as a dependency as suggested in #1455 following recommendations from styled-components:
https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
Resolves #1455

fix: expand styled-component peer dep range

---

CHANGELOG.md
packages/react-static/src/Suspense.js
packages/react-static/src/bootstrapApp.js

Moved out Suspense to a separate file as it was mentioned in https://github.com/react-static/react-static/issues/1497#issuecomment-686178587.
I don't mind improve this in the future, but with this change, it is possible to `import { Suspense } from "react-static"` and use it instead of React Suspense while using `preact`.
The idea is to be able to avoid stubbing `React.default.Suspense` while using `react-static` with `preact`. Even though it is not fully done, thanks to this PR it would be possible to `import { Suspense } from "react-static"` and remove setting `React.default.Suspense` with something like `patch-package`(at least as a temp solution).
Preact 10 support in `react-static`.

Move out Suspense to a separate file

---

CHANGELOG.md
packages/react-static/package.json
yarn.lock

Bumps `git-promise` to 1.0.0, as the current version is [vulnerable](https://app.snyk.io/vuln/SNYK-JS-GITPROMISE-567476) to remote code execution
This vulnerability can cause failing dependency audit pipelines on projects that depend on `react-static`

fix: Bump git-promise to 1.0.0

---

CHANGELOG.md
packages/react-static/src/utils/__tests__/chunkBuilder.test.js
packages/react-static/src/utils/chunkBuilder.js

When the output directory (`config.paths.dist`) is changed to somewhere outside the working directory, there's a lot of warning messages during build.
To reproduce the problem:
```
react-static create --template basic
```
Run `yarn build` right away and it works fine.
Add to `static.config.js` a `paths.dist` property that points somewhere outside the working directory.
```
export default {
paths: {
dist: '/tmp/react-static'
},
getRoutes: ...,
plugins: ...,
}
```
Run `yarn build` again and it gives a bunch of warnings.
```
Exporting HTML across 4 threads...
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/pages/404 in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of …
```

Fix mismatched chunk names

---

CHANGELOG.md
packages/react-static-plugin-react-router/src/browser.api.js

The [`basePath`](https://github.com/react-static/react-static/blob/master/docs/config.md#basepath) configuration in `static.config.js` doesn't work properly with [`react-static-plugin-react-router`](https://github.com/react-static/react-static/tree/master/packages/react-static-plugin-react-router). 
(`basePath` doesn't work with Reach Router either, but that's a Reach Router problem, as mentioned in https://github.com/react-static/react-static/issues/1474.)
Once you have a react-static site set up with react router plugin and `basePath` configured. It builds without a fuzz, and you can see your site at http://localhost:3000/some_basepath/. But if you click on a `/about` link expecting to go to http://localhost:3000/some_basepath/about, the page will show up properly but the browser url …

Fix basepath configuration for React Router.

---

CHANGELOG.md
packages/react-static/src/static/webpack/rules/cssLoader.js

This PR adds `hmr` when configuring `extract-css-chunks-webpack-plugin` for hot-reloading. See #1504 for details.

Update extract-css-chunks-webpack-plugin options for hot-reload

---

docs/guides/material-ui.md
packages/react-static-plugin-jss/src/node.api.js

Resolves #1179 as mentioned [here](https://github.com/react-static/react-static/issues/1179#issuecomment-751135591). The plugin was out of date and no longer worked on the latest version of MUI.
Note: This does not update the generic JSS plugin (released as a separate node module) which may or may not still work (I haven't tried it with anything other than MUI). Rather than doing the work of maintaining a separate plugin for MUI, I think the community would be better served keeping this simpler guide updated and lettings folks customize according to need.
Thanks to @Herohtar and @6pm earlier for their work debugging this.

[docs] Update Material UI guide for MUI v4

---

CHANGELOG.md
packages/react-static/src/browser/components/Routes.js

I was following the [animated routes guide](https://github.com/react-static/react-static/blob/master/docs/guides/animated-routes.md), and everything seemed to be working well. Then, I accidentally navigated to a non-existent route and realized that instead of my 404 page rendering automatically as it does when I don't use the `render` prop of `Routes`, nothing at all was rendered.
I dug into the implementation of `getComponentForPath` and realized that it always returns `false` if `routePath` does not match anything, even if a 404 template exists. This is due to [this line of code](https://github.com/react-static/react-static/blob/3793552f6e9ff921cb8480768a7438e386f6194b/packages/react-static/src/browser/components/Routes.js#L43) which should contain a `&&` instead of a `||` - and thus …

Make getComponentForPath properly return 404 page when route is invalid and 404 page exists

---

CHANGELOG.md
packages/react-static/package.json
yarn.lock

This fixes a high severity vulnerability identified by running `npm audit`, as documented in #1554.
`npm audit` identifies a high severity vulnerability, as discussed in #1554. This change fixes that vulnerability.

Bump axios from 0.19.0 to 0.21.1

---

CHANGELOG.md
packages/react-static-plugin-emotion/package.json
packages/react-static-plugin-evergreen/package.json
packages/react-static-plugin-jss/package.json
packages/react-static-plugin-reach-router/package.json
packages/react-static-plugin-react-location/package.json
packages/react-static-plugin-react-router/package.json
packages/react-static-plugin-styled-components/package.json
packages/react-static/package.json
yarn.lock

React doesn't need to be a `dependency` of any of the `react-static`
packages, but a `peerDependency` instead. This allows users of the
library to upgrade React versions without waiting for `react-static` to
upgrade its version.
Also removes `react-hot-loader` from `dependencies` as it was already
declared a `peerDependency`.
Add support for React 17
It allows users of the library to more freely upgrade their React
version

Move react to peerDependency for more lenient version control

---

CHANGELOG.md
packages/react-static/src/Suspense.js

Store original React.Suspense in the Suspense component instead of using the default, which will be itself.
closes #1564

Prevent endless suspense loop

---

packages/react-static-plugin-sitemap/README.md

This fixes a typo in the readme for the react-static-plugin-sitemap plugin
The documentation should be accurate

Fix typo in react-static-plugin-sitemap readme

---

CHANGELOG.md
docs/plugins/node-api.md
packages/react-static/src/static/exportRoute.js
packages/react-static/src/static/plugins.js
packages/react-static/src/static/webpack/runDevServer.js

Allow plugins to modify routeInfo to for example add or modify the data that is used on a page.
- Call new routeInfo hook in exportRoute
- Call new routeInfo hook in dev server for each request
- Extract valid hooks from object, to remove extra list
#1566

Allow plugins to modify routeInfo

---

CHANGELOG.md
packages/react-static/src/static/webpack/webpack.config.dev.js
packages/react-static/src/static/webpack/webpack.config.prod.js

webpack.output.publicPath for production deployment should use assetsPath value

REACT_STATIC_ASSETS_PATH as webpack.output.publicPath

---

CHANGELOG.md
packages/react-static-plugin-emotion/package.json
packages/react-static-plugin-emotion/src/browser.api.js
packages/react-static-plugin-emotion/src/node.api.js

Updating plugin and dependencies of emotion
Current plugin doesn't build with emotion 11

Update emotion-plugin to the latest version

---

CHANGELOG.md
packages/react-static/src/browser/index.js

At the moment, there is no indication why the 404 page is displayed instead of the actual page

Show a warning in development mode, when a template file does not have a default export

---

CHANGELOG.md
packages/react-static-plugin-sitemap/src/__test__/__snapshots__/buildXML.test.js.snap
packages/react-static-plugin-sitemap/src/__test__/buildXML.test.js
packages/react-static-plugin-sitemap/src/buildXML.js

Sitemap generation in staging context had a bug that would add too many
linebreaks
Fixes #1587

Fix generation of staging sitemap

---

CHANGELOG.md
packages/react-static-plugin-sass/README.md
packages/react-static-plugin-sass/package.json
packages/react-static-plugin-sass/src/node.api.js
yarn.lock

Migrate node-sass usage to Dart Sass library
- node-sass has been deprecated (https://sass-lang.com/blog/libsass-is-deprecated) and it is recommended to switch to use Dart Sass instead.
- This allows users to actually use all SASS language features as node-sass has been lagging behind in feature parity for years.
- This change is required for us to support Node 16

Migrate to use Dart Sass instead of Node Sass

---

CHANGELOG.md
packages/react-static-plugin-sitemap/README.md
packages/react-static-plugin-sitemap/src/__test__/buildXML.test.js
packages/react-static-plugin-sitemap/src/buildXML.js

Setting `noindex` to true for a route should exclude it from the
sitemap, but this is not happening. There is a interface mismatch
between the state and how `buildXML` handles the option

Ensure `noindex` urls are excluded from sitemap.xml
